//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Commands struct {
	ID                   int32 `sql:"primary_key"`
	ReplayID             int32
	PlayerID             int32
	Frame                int32
	SecondsFromGameStart int32
	RunAt                time.Time
	ActionType           string
	X                    *int32
	Y                    *int32
	IsQueued             *bool
	OrderName            *string
	UnitType             *string
	UnitTypes            *string
	TechName             *string
	UpgradeName          *string
	HotkeyType           *string
	HotkeyGroup          *int32
	GameSpeed            *string
	VisionPlayerIds      *string
	AlliancePlayerIds    *string
	IsAlliedVictory      *bool
	GeneralData          *string
	ChatMessage          *string
	LeaveReason          *string
}
