//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Dashboards struct {
	URL         string `sql:"primary_key"`
	Name        string
	Description *string
	CreatedAt   *time.Time
}
