//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type DashboardWidgets struct {
	ID          int64 `sql:"primary_key"`
	DashboardID *string
	WidgetOrder *int64
	Name        string
	Description *string
	Config      string
	Query       string
	CreatedAt   *time.Time
	UpdatedAt   *time.Time
}
