//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type DetectedPatternsReplayTeam struct {
	ReplayID       int32  `sql:"primary_key"`
	Team           int32  `sql:"primary_key"`
	PatternName    string `sql:"primary_key"`
	ValueBool      *bool
	ValueInt       *int32
	ValueString    *string
	ValueTimestamp *int64
}
