//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Players struct {
	ID                  int32 `sql:"primary_key"`
	ReplayID            int32
	Name                string
	Race                string
	Type                string
	Color               string
	Team                int32
	IsObserver          bool
	Apm                 int32
	Eapm                int32
	IsWinner            bool
	StartLocationX      *int32
	StartLocationY      *int32
	StartLocationOclock *int32
}
