//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Replays struct {
	ID              int32 `sql:"primary_key"`
	FilePath        string
	FileChecksum    string
	FileName        string
	CreatedAt       time.Time
	ReplayDate      time.Time
	Title           *string
	Host            *string
	MapName         string
	MapWidth        int32
	MapHeight       int32
	DurationSeconds int32
	FrameCount      int32
	EngineVersion   string
	Engine          string
	GameSpeed       string
	GameType        string
	HomeTeamSize    string
	AvailSlotsCount int32
}
