package models

const (
	TechStimPacks         = "Stim Packs"
	TechLockdown          = "Lockdown"
	TechEMPShockwave      = "EMP Shockwave"
	TechSpiderMines       = "Spider Mines"
	TechScannerSweep      = "Scanner Sweep"
	TechTankSiegeMode     = "Tank Siege Mode"
	TechDefensiveMatrix   = "Defensive Matrix"
	TechIrradiate         = "Irradiate"
	TechYamatoGun         = "Yamato Gun"
	TechCloakingField     = "Cloaking Field"
	TechPersonnelCloaking = "Personnel Cloaking"
	TechBurrowing         = "Burrowing"
	TechInfestation       = "Infestation"
	TechSpawnBroodlings   = "Spawn Broodlings"
	TechDarkSwarm         = "Dark Swarm"
	TechPlague            = "Plague"
	TechConsume           = "Consume"
	TechEnsnare           = "Ensnare"
	TechParasite          = "Parasite"
	TechPsionicStorm      = "Psionic Storm"
	TechHallucination     = "Hallucination"
	TechRecall            = "Recall"
	TechStasisField       = "Stasis Field"
	TechArchonWarp        = "Archon Warp"
	TechRestoration       = "Restoration"
	TechDisruptionWeb     = "Disruption Web"
	TechUnused26          = "Unused 26"
	TechMindControl       = "Mind Control"
	TechDarkArchonMeld    = "Dark Archon Meld"
	TechFeedback          = "Feedback"
	TechOpticalFlare      = "Optical Flare"
	TechMaelstrom         = "Maelstrom"
	TechLurkerAspect      = "Lurker Aspect"
	TechUnused33          = "Unused 33"
	TechHealing           = "Healing"
)
