//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Commands = newCommandsTable("public", "commands", "")

type commandsTable struct {
	postgres.Table

	// Columns
	ID                   postgres.ColumnInteger
	ReplayID             postgres.ColumnInteger
	PlayerID             postgres.ColumnInteger
	Frame                postgres.ColumnInteger
	SecondsFromGameStart postgres.ColumnInteger
	RunAt                postgres.ColumnTimestampz
	ActionType           postgres.ColumnString
	X                    postgres.ColumnInteger
	Y                    postgres.ColumnInteger
	IsQueued             postgres.ColumnBool
	OrderName            postgres.ColumnString
	UnitType             postgres.ColumnString
	UnitTypes            postgres.ColumnString
	TechName             postgres.ColumnString
	UpgradeName          postgres.ColumnString
	HotkeyType           postgres.ColumnString
	HotkeyGroup          postgres.ColumnInteger
	GameSpeed            postgres.ColumnString
	VisionPlayerIds      postgres.ColumnString
	AlliancePlayerIds    postgres.ColumnString
	IsAlliedVictory      postgres.ColumnBool
	GeneralData          postgres.ColumnString
	ChatMessage          postgres.ColumnString
	LeaveReason          postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type CommandsTable struct {
	commandsTable

	EXCLUDED commandsTable
}

// AS creates new CommandsTable with assigned alias
func (a CommandsTable) AS(alias string) *CommandsTable {
	return newCommandsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CommandsTable with assigned schema name
func (a CommandsTable) FromSchema(schemaName string) *CommandsTable {
	return newCommandsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CommandsTable with assigned table prefix
func (a CommandsTable) WithPrefix(prefix string) *CommandsTable {
	return newCommandsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CommandsTable with assigned table suffix
func (a CommandsTable) WithSuffix(suffix string) *CommandsTable {
	return newCommandsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCommandsTable(schemaName, tableName, alias string) *CommandsTable {
	return &CommandsTable{
		commandsTable: newCommandsTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newCommandsTableImpl("", "excluded", ""),
	}
}

func newCommandsTableImpl(schemaName, tableName, alias string) commandsTable {
	var (
		IDColumn                   = postgres.IntegerColumn("id")
		ReplayIDColumn             = postgres.IntegerColumn("replay_id")
		PlayerIDColumn             = postgres.IntegerColumn("player_id")
		FrameColumn                = postgres.IntegerColumn("frame")
		SecondsFromGameStartColumn = postgres.IntegerColumn("seconds_from_game_start")
		RunAtColumn                = postgres.TimestampzColumn("run_at")
		ActionTypeColumn           = postgres.StringColumn("action_type")
		XColumn                    = postgres.IntegerColumn("x")
		YColumn                    = postgres.IntegerColumn("y")
		IsQueuedColumn             = postgres.BoolColumn("is_queued")
		OrderNameColumn            = postgres.StringColumn("order_name")
		UnitTypeColumn             = postgres.StringColumn("unit_type")
		UnitTypesColumn            = postgres.StringColumn("unit_types")
		TechNameColumn             = postgres.StringColumn("tech_name")
		UpgradeNameColumn          = postgres.StringColumn("upgrade_name")
		HotkeyTypeColumn           = postgres.StringColumn("hotkey_type")
		HotkeyGroupColumn          = postgres.IntegerColumn("hotkey_group")
		GameSpeedColumn            = postgres.StringColumn("game_speed")
		VisionPlayerIdsColumn      = postgres.StringColumn("vision_player_ids")
		AlliancePlayerIdsColumn    = postgres.StringColumn("alliance_player_ids")
		IsAlliedVictoryColumn      = postgres.BoolColumn("is_allied_victory")
		GeneralDataColumn          = postgres.StringColumn("general_data")
		ChatMessageColumn          = postgres.StringColumn("chat_message")
		LeaveReasonColumn          = postgres.StringColumn("leave_reason")
		allColumns                 = postgres.ColumnList{IDColumn, ReplayIDColumn, PlayerIDColumn, FrameColumn, SecondsFromGameStartColumn, RunAtColumn, ActionTypeColumn, XColumn, YColumn, IsQueuedColumn, OrderNameColumn, UnitTypeColumn, UnitTypesColumn, TechNameColumn, UpgradeNameColumn, HotkeyTypeColumn, HotkeyGroupColumn, GameSpeedColumn, VisionPlayerIdsColumn, AlliancePlayerIdsColumn, IsAlliedVictoryColumn, GeneralDataColumn, ChatMessageColumn, LeaveReasonColumn}
		mutableColumns             = postgres.ColumnList{ReplayIDColumn, PlayerIDColumn, FrameColumn, SecondsFromGameStartColumn, RunAtColumn, ActionTypeColumn, XColumn, YColumn, IsQueuedColumn, OrderNameColumn, UnitTypeColumn, UnitTypesColumn, TechNameColumn, UpgradeNameColumn, HotkeyTypeColumn, HotkeyGroupColumn, GameSpeedColumn, VisionPlayerIdsColumn, AlliancePlayerIdsColumn, IsAlliedVictoryColumn, GeneralDataColumn, ChatMessageColumn, LeaveReasonColumn}
		defaultColumns             = postgres.ColumnList{IDColumn}
	)

	return commandsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                   IDColumn,
		ReplayID:             ReplayIDColumn,
		PlayerID:             PlayerIDColumn,
		Frame:                FrameColumn,
		SecondsFromGameStart: SecondsFromGameStartColumn,
		RunAt:                RunAtColumn,
		ActionType:           ActionTypeColumn,
		X:                    XColumn,
		Y:                    YColumn,
		IsQueued:             IsQueuedColumn,
		OrderName:            OrderNameColumn,
		UnitType:             UnitTypeColumn,
		UnitTypes:            UnitTypesColumn,
		TechName:             TechNameColumn,
		UpgradeName:          UpgradeNameColumn,
		HotkeyType:           HotkeyTypeColumn,
		HotkeyGroup:          HotkeyGroupColumn,
		GameSpeed:            GameSpeedColumn,
		VisionPlayerIds:      VisionPlayerIdsColumn,
		AlliancePlayerIds:    AlliancePlayerIdsColumn,
		IsAlliedVictory:      IsAlliedVictoryColumn,
		GeneralData:          GeneralDataColumn,
		ChatMessage:          ChatMessageColumn,
		LeaveReason:          LeaveReasonColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
