//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Dashboards = newDashboardsTable("public", "dashboards", "")

type dashboardsTable struct {
	postgres.Table

	// Columns
	URL         postgres.ColumnString
	Name        postgres.ColumnString
	Description postgres.ColumnString
	CreatedAt   postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type DashboardsTable struct {
	dashboardsTable

	EXCLUDED dashboardsTable
}

// AS creates new DashboardsTable with assigned alias
func (a DashboardsTable) AS(alias string) *DashboardsTable {
	return newDashboardsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new DashboardsTable with assigned schema name
func (a DashboardsTable) FromSchema(schemaName string) *DashboardsTable {
	return newDashboardsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new DashboardsTable with assigned table prefix
func (a DashboardsTable) WithPrefix(prefix string) *DashboardsTable {
	return newDashboardsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new DashboardsTable with assigned table suffix
func (a DashboardsTable) WithSuffix(suffix string) *DashboardsTable {
	return newDashboardsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newDashboardsTable(schemaName, tableName, alias string) *DashboardsTable {
	return &DashboardsTable{
		dashboardsTable: newDashboardsTableImpl(schemaName, tableName, alias),
		EXCLUDED:        newDashboardsTableImpl("", "excluded", ""),
	}
}

func newDashboardsTableImpl(schemaName, tableName, alias string) dashboardsTable {
	var (
		URLColumn         = postgres.StringColumn("url")
		NameColumn        = postgres.StringColumn("name")
		DescriptionColumn = postgres.StringColumn("description")
		CreatedAtColumn   = postgres.TimestampColumn("created_at")
		allColumns        = postgres.ColumnList{URLColumn, NameColumn, DescriptionColumn, CreatedAtColumn}
		mutableColumns    = postgres.ColumnList{NameColumn, DescriptionColumn, CreatedAtColumn}
		defaultColumns    = postgres.ColumnList{CreatedAtColumn}
	)

	return dashboardsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		URL:         URLColumn,
		Name:        NameColumn,
		Description: DescriptionColumn,
		CreatedAt:   CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
