//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var DashboardWidgetPromptHistory = newDashboardWidgetPromptHistoryTable("public", "dashboard_widget_prompt_history", "")

type dashboardWidgetPromptHistoryTable struct {
	postgres.Table

	// Columns
	ID            postgres.ColumnInteger
	WidgetID      postgres.ColumnInteger
	PromptHistory postgres.ColumnString
	CreatedAt     postgres.ColumnTimestamp
	UpdatedAt     postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type DashboardWidgetPromptHistoryTable struct {
	dashboardWidgetPromptHistoryTable

	EXCLUDED dashboardWidgetPromptHistoryTable
}

// AS creates new DashboardWidgetPromptHistoryTable with assigned alias
func (a DashboardWidgetPromptHistoryTable) AS(alias string) *DashboardWidgetPromptHistoryTable {
	return newDashboardWidgetPromptHistoryTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new DashboardWidgetPromptHistoryTable with assigned schema name
func (a DashboardWidgetPromptHistoryTable) FromSchema(schemaName string) *DashboardWidgetPromptHistoryTable {
	return newDashboardWidgetPromptHistoryTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new DashboardWidgetPromptHistoryTable with assigned table prefix
func (a DashboardWidgetPromptHistoryTable) WithPrefix(prefix string) *DashboardWidgetPromptHistoryTable {
	return newDashboardWidgetPromptHistoryTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new DashboardWidgetPromptHistoryTable with assigned table suffix
func (a DashboardWidgetPromptHistoryTable) WithSuffix(suffix string) *DashboardWidgetPromptHistoryTable {
	return newDashboardWidgetPromptHistoryTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newDashboardWidgetPromptHistoryTable(schemaName, tableName, alias string) *DashboardWidgetPromptHistoryTable {
	return &DashboardWidgetPromptHistoryTable{
		dashboardWidgetPromptHistoryTable: newDashboardWidgetPromptHistoryTableImpl(schemaName, tableName, alias),
		EXCLUDED:                          newDashboardWidgetPromptHistoryTableImpl("", "excluded", ""),
	}
}

func newDashboardWidgetPromptHistoryTableImpl(schemaName, tableName, alias string) dashboardWidgetPromptHistoryTable {
	var (
		IDColumn            = postgres.IntegerColumn("id")
		WidgetIDColumn      = postgres.IntegerColumn("widget_id")
		PromptHistoryColumn = postgres.StringColumn("prompt_history")
		CreatedAtColumn     = postgres.TimestampColumn("created_at")
		UpdatedAtColumn     = postgres.TimestampColumn("updated_at")
		allColumns          = postgres.ColumnList{IDColumn, WidgetIDColumn, PromptHistoryColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns      = postgres.ColumnList{WidgetIDColumn, PromptHistoryColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns      = postgres.ColumnList{IDColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return dashboardWidgetPromptHistoryTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		WidgetID:      WidgetIDColumn,
		PromptHistory: PromptHistoryColumn,
		CreatedAt:     CreatedAtColumn,
		UpdatedAt:     UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
