//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var DashboardWidgets = newDashboardWidgetsTable("public", "dashboard_widgets", "")

type dashboardWidgetsTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnInteger
	DashboardID postgres.ColumnString
	WidgetOrder postgres.ColumnInteger
	Name        postgres.ColumnString
	Description postgres.ColumnString
	Config      postgres.ColumnString
	Query       postgres.ColumnString
	CreatedAt   postgres.ColumnTimestamp
	UpdatedAt   postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type DashboardWidgetsTable struct {
	dashboardWidgetsTable

	EXCLUDED dashboardWidgetsTable
}

// AS creates new DashboardWidgetsTable with assigned alias
func (a DashboardWidgetsTable) AS(alias string) *DashboardWidgetsTable {
	return newDashboardWidgetsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new DashboardWidgetsTable with assigned schema name
func (a DashboardWidgetsTable) FromSchema(schemaName string) *DashboardWidgetsTable {
	return newDashboardWidgetsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new DashboardWidgetsTable with assigned table prefix
func (a DashboardWidgetsTable) WithPrefix(prefix string) *DashboardWidgetsTable {
	return newDashboardWidgetsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new DashboardWidgetsTable with assigned table suffix
func (a DashboardWidgetsTable) WithSuffix(suffix string) *DashboardWidgetsTable {
	return newDashboardWidgetsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newDashboardWidgetsTable(schemaName, tableName, alias string) *DashboardWidgetsTable {
	return &DashboardWidgetsTable{
		dashboardWidgetsTable: newDashboardWidgetsTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newDashboardWidgetsTableImpl("", "excluded", ""),
	}
}

func newDashboardWidgetsTableImpl(schemaName, tableName, alias string) dashboardWidgetsTable {
	var (
		IDColumn          = postgres.IntegerColumn("id")
		DashboardIDColumn = postgres.StringColumn("dashboard_id")
		WidgetOrderColumn = postgres.IntegerColumn("widget_order")
		NameColumn        = postgres.StringColumn("name")
		DescriptionColumn = postgres.StringColumn("description")
		ConfigColumn      = postgres.StringColumn("config")
		QueryColumn       = postgres.StringColumn("query")
		CreatedAtColumn   = postgres.TimestampColumn("created_at")
		UpdatedAtColumn   = postgres.TimestampColumn("updated_at")
		allColumns        = postgres.ColumnList{IDColumn, DashboardIDColumn, WidgetOrderColumn, NameColumn, DescriptionColumn, ConfigColumn, QueryColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns    = postgres.ColumnList{DashboardIDColumn, WidgetOrderColumn, NameColumn, DescriptionColumn, ConfigColumn, QueryColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns    = postgres.ColumnList{IDColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return dashboardWidgetsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		DashboardID: DashboardIDColumn,
		WidgetOrder: WidgetOrderColumn,
		Name:        NameColumn,
		Description: DescriptionColumn,
		Config:      ConfigColumn,
		Query:       QueryColumn,
		CreatedAt:   CreatedAtColumn,
		UpdatedAt:   UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
