//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var DetectedPatternsReplayPlayer = newDetectedPatternsReplayPlayerTable("public", "detected_patterns_replay_player", "")

type detectedPatternsReplayPlayerTable struct {
	postgres.Table

	// Columns
	ReplayID       postgres.ColumnInteger
	PlayerID       postgres.ColumnInteger
	PatternName    postgres.ColumnString
	ValueBool      postgres.ColumnBool
	ValueInt       postgres.ColumnInteger
	ValueString    postgres.ColumnString
	ValueTimestamp postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type DetectedPatternsReplayPlayerTable struct {
	detectedPatternsReplayPlayerTable

	EXCLUDED detectedPatternsReplayPlayerTable
}

// AS creates new DetectedPatternsReplayPlayerTable with assigned alias
func (a DetectedPatternsReplayPlayerTable) AS(alias string) *DetectedPatternsReplayPlayerTable {
	return newDetectedPatternsReplayPlayerTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new DetectedPatternsReplayPlayerTable with assigned schema name
func (a DetectedPatternsReplayPlayerTable) FromSchema(schemaName string) *DetectedPatternsReplayPlayerTable {
	return newDetectedPatternsReplayPlayerTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new DetectedPatternsReplayPlayerTable with assigned table prefix
func (a DetectedPatternsReplayPlayerTable) WithPrefix(prefix string) *DetectedPatternsReplayPlayerTable {
	return newDetectedPatternsReplayPlayerTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new DetectedPatternsReplayPlayerTable with assigned table suffix
func (a DetectedPatternsReplayPlayerTable) WithSuffix(suffix string) *DetectedPatternsReplayPlayerTable {
	return newDetectedPatternsReplayPlayerTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newDetectedPatternsReplayPlayerTable(schemaName, tableName, alias string) *DetectedPatternsReplayPlayerTable {
	return &DetectedPatternsReplayPlayerTable{
		detectedPatternsReplayPlayerTable: newDetectedPatternsReplayPlayerTableImpl(schemaName, tableName, alias),
		EXCLUDED:                          newDetectedPatternsReplayPlayerTableImpl("", "excluded", ""),
	}
}

func newDetectedPatternsReplayPlayerTableImpl(schemaName, tableName, alias string) detectedPatternsReplayPlayerTable {
	var (
		ReplayIDColumn       = postgres.IntegerColumn("replay_id")
		PlayerIDColumn       = postgres.IntegerColumn("player_id")
		PatternNameColumn    = postgres.StringColumn("pattern_name")
		ValueBoolColumn      = postgres.BoolColumn("value_bool")
		ValueIntColumn       = postgres.IntegerColumn("value_int")
		ValueStringColumn    = postgres.StringColumn("value_string")
		ValueTimestampColumn = postgres.IntegerColumn("value_timestamp")
		allColumns           = postgres.ColumnList{ReplayIDColumn, PlayerIDColumn, PatternNameColumn, ValueBoolColumn, ValueIntColumn, ValueStringColumn, ValueTimestampColumn}
		mutableColumns       = postgres.ColumnList{ValueBoolColumn, ValueIntColumn, ValueStringColumn, ValueTimestampColumn}
		defaultColumns       = postgres.ColumnList{}
	)

	return detectedPatternsReplayPlayerTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ReplayID:       ReplayIDColumn,
		PlayerID:       PlayerIDColumn,
		PatternName:    PatternNameColumn,
		ValueBool:      ValueBoolColumn,
		ValueInt:       ValueIntColumn,
		ValueString:    ValueStringColumn,
		ValueTimestamp: ValueTimestampColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
