//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var DetectedPatternsReplayTeam = newDetectedPatternsReplayTeamTable("public", "detected_patterns_replay_team", "")

type detectedPatternsReplayTeamTable struct {
	postgres.Table

	// Columns
	ReplayID       postgres.ColumnInteger
	Team           postgres.ColumnInteger
	PatternName    postgres.ColumnString
	ValueBool      postgres.ColumnBool
	ValueInt       postgres.ColumnInteger
	ValueString    postgres.ColumnString
	ValueTimestamp postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type DetectedPatternsReplayTeamTable struct {
	detectedPatternsReplayTeamTable

	EXCLUDED detectedPatternsReplayTeamTable
}

// AS creates new DetectedPatternsReplayTeamTable with assigned alias
func (a DetectedPatternsReplayTeamTable) AS(alias string) *DetectedPatternsReplayTeamTable {
	return newDetectedPatternsReplayTeamTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new DetectedPatternsReplayTeamTable with assigned schema name
func (a DetectedPatternsReplayTeamTable) FromSchema(schemaName string) *DetectedPatternsReplayTeamTable {
	return newDetectedPatternsReplayTeamTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new DetectedPatternsReplayTeamTable with assigned table prefix
func (a DetectedPatternsReplayTeamTable) WithPrefix(prefix string) *DetectedPatternsReplayTeamTable {
	return newDetectedPatternsReplayTeamTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new DetectedPatternsReplayTeamTable with assigned table suffix
func (a DetectedPatternsReplayTeamTable) WithSuffix(suffix string) *DetectedPatternsReplayTeamTable {
	return newDetectedPatternsReplayTeamTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newDetectedPatternsReplayTeamTable(schemaName, tableName, alias string) *DetectedPatternsReplayTeamTable {
	return &DetectedPatternsReplayTeamTable{
		detectedPatternsReplayTeamTable: newDetectedPatternsReplayTeamTableImpl(schemaName, tableName, alias),
		EXCLUDED:                        newDetectedPatternsReplayTeamTableImpl("", "excluded", ""),
	}
}

func newDetectedPatternsReplayTeamTableImpl(schemaName, tableName, alias string) detectedPatternsReplayTeamTable {
	var (
		ReplayIDColumn       = postgres.IntegerColumn("replay_id")
		TeamColumn           = postgres.IntegerColumn("team")
		PatternNameColumn    = postgres.StringColumn("pattern_name")
		ValueBoolColumn      = postgres.BoolColumn("value_bool")
		ValueIntColumn       = postgres.IntegerColumn("value_int")
		ValueStringColumn    = postgres.StringColumn("value_string")
		ValueTimestampColumn = postgres.IntegerColumn("value_timestamp")
		allColumns           = postgres.ColumnList{ReplayIDColumn, TeamColumn, PatternNameColumn, ValueBoolColumn, ValueIntColumn, ValueStringColumn, ValueTimestampColumn}
		mutableColumns       = postgres.ColumnList{ValueBoolColumn, ValueIntColumn, ValueStringColumn, ValueTimestampColumn}
		defaultColumns       = postgres.ColumnList{}
	)

	return detectedPatternsReplayTeamTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ReplayID:       ReplayIDColumn,
		Team:           TeamColumn,
		PatternName:    PatternNameColumn,
		ValueBool:      ValueBoolColumn,
		ValueInt:       ValueIntColumn,
		ValueString:    ValueStringColumn,
		ValueTimestamp: ValueTimestampColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
