//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var DetectedPatternsReplay = newDetectedPatternsReplayTable("public", "detected_patterns_replay", "")

type detectedPatternsReplayTable struct {
	postgres.Table

	// Columns
	ReplayID         postgres.ColumnInteger
	AlgorithmVersion postgres.ColumnInteger
	FilePath         postgres.ColumnString
	FileChecksum     postgres.ColumnString
	PatternName      postgres.ColumnString
	ValueBool        postgres.ColumnBool
	ValueInt         postgres.ColumnInteger
	ValueString      postgres.ColumnString
	ValueTimestamp   postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type DetectedPatternsReplayTable struct {
	detectedPatternsReplayTable

	EXCLUDED detectedPatternsReplayTable
}

// AS creates new DetectedPatternsReplayTable with assigned alias
func (a DetectedPatternsReplayTable) AS(alias string) *DetectedPatternsReplayTable {
	return newDetectedPatternsReplayTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new DetectedPatternsReplayTable with assigned schema name
func (a DetectedPatternsReplayTable) FromSchema(schemaName string) *DetectedPatternsReplayTable {
	return newDetectedPatternsReplayTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new DetectedPatternsReplayTable with assigned table prefix
func (a DetectedPatternsReplayTable) WithPrefix(prefix string) *DetectedPatternsReplayTable {
	return newDetectedPatternsReplayTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new DetectedPatternsReplayTable with assigned table suffix
func (a DetectedPatternsReplayTable) WithSuffix(suffix string) *DetectedPatternsReplayTable {
	return newDetectedPatternsReplayTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newDetectedPatternsReplayTable(schemaName, tableName, alias string) *DetectedPatternsReplayTable {
	return &DetectedPatternsReplayTable{
		detectedPatternsReplayTable: newDetectedPatternsReplayTableImpl(schemaName, tableName, alias),
		EXCLUDED:                    newDetectedPatternsReplayTableImpl("", "excluded", ""),
	}
}

func newDetectedPatternsReplayTableImpl(schemaName, tableName, alias string) detectedPatternsReplayTable {
	var (
		ReplayIDColumn         = postgres.IntegerColumn("replay_id")
		AlgorithmVersionColumn = postgres.IntegerColumn("algorithm_version")
		FilePathColumn         = postgres.StringColumn("file_path")
		FileChecksumColumn     = postgres.StringColumn("file_checksum")
		PatternNameColumn      = postgres.StringColumn("pattern_name")
		ValueBoolColumn        = postgres.BoolColumn("value_bool")
		ValueIntColumn         = postgres.IntegerColumn("value_int")
		ValueStringColumn      = postgres.StringColumn("value_string")
		ValueTimestampColumn   = postgres.IntegerColumn("value_timestamp")
		allColumns             = postgres.ColumnList{ReplayIDColumn, AlgorithmVersionColumn, FilePathColumn, FileChecksumColumn, PatternNameColumn, ValueBoolColumn, ValueIntColumn, ValueStringColumn, ValueTimestampColumn}
		mutableColumns         = postgres.ColumnList{AlgorithmVersionColumn, FilePathColumn, FileChecksumColumn, ValueBoolColumn, ValueIntColumn, ValueStringColumn, ValueTimestampColumn}
		defaultColumns         = postgres.ColumnList{}
	)

	return detectedPatternsReplayTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ReplayID:         ReplayIDColumn,
		AlgorithmVersion: AlgorithmVersionColumn,
		FilePath:         FilePathColumn,
		FileChecksum:     FileChecksumColumn,
		PatternName:      PatternNameColumn,
		ValueBool:        ValueBoolColumn,
		ValueInt:         ValueIntColumn,
		ValueString:      ValueStringColumn,
		ValueTimestamp:   ValueTimestampColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
