//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Players = newPlayersTable("public", "players", "")

type playersTable struct {
	postgres.Table

	// Columns
	ID                  postgres.ColumnInteger
	ReplayID            postgres.ColumnInteger
	Name                postgres.ColumnString
	Race                postgres.ColumnString
	Type                postgres.ColumnString
	Color               postgres.ColumnString
	Team                postgres.ColumnInteger
	IsObserver          postgres.ColumnBool
	Apm                 postgres.ColumnInteger
	Eapm                postgres.ColumnInteger
	IsWinner            postgres.ColumnBool
	StartLocationX      postgres.ColumnInteger
	StartLocationY      postgres.ColumnInteger
	StartLocationOclock postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PlayersTable struct {
	playersTable

	EXCLUDED playersTable
}

// AS creates new PlayersTable with assigned alias
func (a PlayersTable) AS(alias string) *PlayersTable {
	return newPlayersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PlayersTable with assigned schema name
func (a PlayersTable) FromSchema(schemaName string) *PlayersTable {
	return newPlayersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PlayersTable with assigned table prefix
func (a PlayersTable) WithPrefix(prefix string) *PlayersTable {
	return newPlayersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PlayersTable with assigned table suffix
func (a PlayersTable) WithSuffix(suffix string) *PlayersTable {
	return newPlayersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPlayersTable(schemaName, tableName, alias string) *PlayersTable {
	return &PlayersTable{
		playersTable: newPlayersTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newPlayersTableImpl("", "excluded", ""),
	}
}

func newPlayersTableImpl(schemaName, tableName, alias string) playersTable {
	var (
		IDColumn                  = postgres.IntegerColumn("id")
		ReplayIDColumn            = postgres.IntegerColumn("replay_id")
		NameColumn                = postgres.StringColumn("name")
		RaceColumn                = postgres.StringColumn("race")
		TypeColumn                = postgres.StringColumn("type")
		ColorColumn               = postgres.StringColumn("color")
		TeamColumn                = postgres.IntegerColumn("team")
		IsObserverColumn          = postgres.BoolColumn("is_observer")
		ApmColumn                 = postgres.IntegerColumn("apm")
		EapmColumn                = postgres.IntegerColumn("eapm")
		IsWinnerColumn            = postgres.BoolColumn("is_winner")
		StartLocationXColumn      = postgres.IntegerColumn("start_location_x")
		StartLocationYColumn      = postgres.IntegerColumn("start_location_y")
		StartLocationOclockColumn = postgres.IntegerColumn("start_location_oclock")
		allColumns                = postgres.ColumnList{IDColumn, ReplayIDColumn, NameColumn, RaceColumn, TypeColumn, ColorColumn, TeamColumn, IsObserverColumn, ApmColumn, EapmColumn, IsWinnerColumn, StartLocationXColumn, StartLocationYColumn, StartLocationOclockColumn}
		mutableColumns            = postgres.ColumnList{ReplayIDColumn, NameColumn, RaceColumn, TypeColumn, ColorColumn, TeamColumn, IsObserverColumn, ApmColumn, EapmColumn, IsWinnerColumn, StartLocationXColumn, StartLocationYColumn, StartLocationOclockColumn}
		defaultColumns            = postgres.ColumnList{IDColumn}
	)

	return playersTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                  IDColumn,
		ReplayID:            ReplayIDColumn,
		Name:                NameColumn,
		Race:                RaceColumn,
		Type:                TypeColumn,
		Color:               ColorColumn,
		Team:                TeamColumn,
		IsObserver:          IsObserverColumn,
		Apm:                 ApmColumn,
		Eapm:                EapmColumn,
		IsWinner:            IsWinnerColumn,
		StartLocationX:      StartLocationXColumn,
		StartLocationY:      StartLocationYColumn,
		StartLocationOclock: StartLocationOclockColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
