//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Replays = newReplaysTable("public", "replays", "")

type replaysTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnInteger
	FilePath        postgres.ColumnString
	FileChecksum    postgres.ColumnString
	FileName        postgres.ColumnString
	CreatedAt       postgres.ColumnTimestampz
	ReplayDate      postgres.ColumnTimestampz
	Title           postgres.ColumnString
	Host            postgres.ColumnString
	MapName         postgres.ColumnString
	MapWidth        postgres.ColumnInteger
	MapHeight       postgres.ColumnInteger
	DurationSeconds postgres.ColumnInteger
	FrameCount      postgres.ColumnInteger
	EngineVersion   postgres.ColumnString
	Engine          postgres.ColumnString
	GameSpeed       postgres.ColumnString
	GameType        postgres.ColumnString
	HomeTeamSize    postgres.ColumnString
	AvailSlotsCount postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ReplaysTable struct {
	replaysTable

	EXCLUDED replaysTable
}

// AS creates new ReplaysTable with assigned alias
func (a ReplaysTable) AS(alias string) *ReplaysTable {
	return newReplaysTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ReplaysTable with assigned schema name
func (a ReplaysTable) FromSchema(schemaName string) *ReplaysTable {
	return newReplaysTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ReplaysTable with assigned table prefix
func (a ReplaysTable) WithPrefix(prefix string) *ReplaysTable {
	return newReplaysTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ReplaysTable with assigned table suffix
func (a ReplaysTable) WithSuffix(suffix string) *ReplaysTable {
	return newReplaysTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newReplaysTable(schemaName, tableName, alias string) *ReplaysTable {
	return &ReplaysTable{
		replaysTable: newReplaysTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newReplaysTableImpl("", "excluded", ""),
	}
}

func newReplaysTableImpl(schemaName, tableName, alias string) replaysTable {
	var (
		IDColumn              = postgres.IntegerColumn("id")
		FilePathColumn        = postgres.StringColumn("file_path")
		FileChecksumColumn    = postgres.StringColumn("file_checksum")
		FileNameColumn        = postgres.StringColumn("file_name")
		CreatedAtColumn       = postgres.TimestampzColumn("created_at")
		ReplayDateColumn      = postgres.TimestampzColumn("replay_date")
		TitleColumn           = postgres.StringColumn("title")
		HostColumn            = postgres.StringColumn("host")
		MapNameColumn         = postgres.StringColumn("map_name")
		MapWidthColumn        = postgres.IntegerColumn("map_width")
		MapHeightColumn       = postgres.IntegerColumn("map_height")
		DurationSecondsColumn = postgres.IntegerColumn("duration_seconds")
		FrameCountColumn      = postgres.IntegerColumn("frame_count")
		EngineVersionColumn   = postgres.StringColumn("engine_version")
		EngineColumn          = postgres.StringColumn("engine")
		GameSpeedColumn       = postgres.StringColumn("game_speed")
		GameTypeColumn        = postgres.StringColumn("game_type")
		HomeTeamSizeColumn    = postgres.StringColumn("home_team_size")
		AvailSlotsCountColumn = postgres.IntegerColumn("avail_slots_count")
		allColumns            = postgres.ColumnList{IDColumn, FilePathColumn, FileChecksumColumn, FileNameColumn, CreatedAtColumn, ReplayDateColumn, TitleColumn, HostColumn, MapNameColumn, MapWidthColumn, MapHeightColumn, DurationSecondsColumn, FrameCountColumn, EngineVersionColumn, EngineColumn, GameSpeedColumn, GameTypeColumn, HomeTeamSizeColumn, AvailSlotsCountColumn}
		mutableColumns        = postgres.ColumnList{FilePathColumn, FileChecksumColumn, FileNameColumn, CreatedAtColumn, ReplayDateColumn, TitleColumn, HostColumn, MapNameColumn, MapWidthColumn, MapHeightColumn, DurationSecondsColumn, FrameCountColumn, EngineVersionColumn, EngineColumn, GameSpeedColumn, GameTypeColumn, HomeTeamSizeColumn, AvailSlotsCountColumn}
		defaultColumns        = postgres.ColumnList{IDColumn}
	)

	return replaysTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		FilePath:        FilePathColumn,
		FileChecksum:    FileChecksumColumn,
		FileName:        FileNameColumn,
		CreatedAt:       CreatedAtColumn,
		ReplayDate:      ReplayDateColumn,
		Title:           TitleColumn,
		Host:            HostColumn,
		MapName:         MapNameColumn,
		MapWidth:        MapWidthColumn,
		MapHeight:       MapHeightColumn,
		DurationSeconds: DurationSecondsColumn,
		FrameCount:      FrameCountColumn,
		EngineVersion:   EngineVersionColumn,
		Engine:          EngineColumn,
		GameSpeed:       GameSpeedColumn,
		GameType:        GameTypeColumn,
		HomeTeamSize:    HomeTeamSizeColumn,
		AvailSlotsCount: AvailSlotsCountColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
