//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	Commands = Commands.FromSchema(schema)
	DashboardWidgetPromptHistory = DashboardWidgetPromptHistory.FromSchema(schema)
	DashboardWidgets = DashboardWidgets.FromSchema(schema)
	Dashboards = Dashboards.FromSchema(schema)
	DetectedPatternsReplay = DetectedPatternsReplay.FromSchema(schema)
	DetectedPatternsReplayPlayer = DetectedPatternsReplayPlayer.FromSchema(schema)
	DetectedPatternsReplayTeam = DetectedPatternsReplayTeam.FromSchema(schema)
	Players = Players.FromSchema(schema)
	Replays = Replays.FromSchema(schema)
	SchemaMigrations = SchemaMigrations.FromSchema(schema)
}
