package dashboard

import (
	"context"

	"encoding/json"
	"net/http"

	"github.com/marianogappa/screpdb/internal/dashboard/apigen"
)

// Code generated by gen_openapi_bridge. DO NOT EDIT.
type GetGlobalReplayFilterConfigJSONResponse struct {
	Payload any
}

func (response GetGlobalReplayFilterConfigJSONResponse) VisitGetGlobalReplayFilterConfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)

	return json.NewEncoder(w).Encode(response.Payload)
}

func (a *openAPIStrictAdapter) GetGlobalReplayFilterConfig(ctx context.Context, request apigen.GetGlobalReplayFilterConfigRequestObject) (apigen.GetGlobalReplayFilterConfigResponseObject, error) {
	return responseFromPayload(ctx, request, a.service.GetGlobalReplayFilterConfig, func(value any) apigen.GetGlobalReplayFilterConfigResponseObject {
		return GetGlobalReplayFilterConfigJSONResponse{Payload: value}
	})
}

type UpdateGlobalReplayFilterConfigJSONResponse struct {
	Payload any
}

func (response UpdateGlobalReplayFilterConfigJSONResponse) VisitUpdateGlobalReplayFilterConfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)

	return json.NewEncoder(w).Encode(response.Payload)
}

func (a *openAPIStrictAdapter) UpdateGlobalReplayFilterConfig(ctx context.Context, request apigen.UpdateGlobalReplayFilterConfigRequestObject) (apigen.UpdateGlobalReplayFilterConfigResponseObject, error) {
	return responseFromPayload(ctx, request, a.service.UpdateGlobalReplayFilterConfig, func(value any) apigen.UpdateGlobalReplayFilterConfigResponseObject {
		return UpdateGlobalReplayFilterConfigJSONResponse{Payload: value}
	})
}

type GetLibrarySettingsJSONResponse struct {
	Payload any
}

func (response GetLibrarySettingsJSONResponse) VisitGetLibrarySettingsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)

	return json.NewEncoder(w).Encode(response.Payload)
}

func (a *openAPIStrictAdapter) GetLibrarySettings(ctx context.Context, request apigen.GetLibrarySettingsRequestObject) (apigen.GetLibrarySettingsResponseObject, error) {
	return responseFromPayload(ctx, request, a.service.GetLibrarySettings, func(value any) apigen.GetLibrarySettingsResponseObject {
		return GetLibrarySettingsJSONResponse{Payload: value}
	})
}

type UpdateLibrarySettingsJSONResponse struct {
	Payload any
}

func (response UpdateLibrarySettingsJSONResponse) VisitUpdateLibrarySettingsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)

	return json.NewEncoder(w).Encode(response.Payload)
}

func (a *openAPIStrictAdapter) UpdateLibrarySettings(ctx context.Context, request apigen.UpdateLibrarySettingsRequestObject) (apigen.UpdateLibrarySettingsResponseObject, error) {
	return responseFromPayload(ctx, request, a.service.UpdateLibrarySettings, func(value any) apigen.UpdateLibrarySettingsResponseObject {
		return UpdateLibrarySettingsJSONResponse{Payload: value}
	})
}

type GamesListJSONResponse struct {
	Payload any
}

func (response GamesListJSONResponse) VisitGamesListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)

	return json.NewEncoder(w).Encode(response.Payload)
}

func (a *openAPIStrictAdapter) GamesList(ctx context.Context, request apigen.GamesListRequestObject) (apigen.GamesListResponseObject, error) {
	return responseFromPayload(ctx, request, a.service.GamesList, func(value any) apigen.GamesListResponseObject { return GamesListJSONResponse{Payload: value} })
}

type GameDetailJSONResponse struct {
	Payload any
}

func (response GameDetailJSONResponse) VisitGameDetailResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)

	return json.NewEncoder(w).Encode(response.Payload)
}

func (a *openAPIStrictAdapter) GameDetail(ctx context.Context, request apigen.GameDetailRequestObject) (apigen.GameDetailResponseObject, error) {
	return responseFromPayload(ctx, request, a.service.GameDetail, func(value any) apigen.GameDetailResponseObject { return GameDetailJSONResponse{Payload: value} })
}

type GameHotkeysJSONResponse struct {
	Payload any
}

func (response GameHotkeysJSONResponse) VisitGameHotkeysResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)

	return json.NewEncoder(w).Encode(response.Payload)
}

func (a *openAPIStrictAdapter) GameHotkeys(ctx context.Context, request apigen.GameHotkeysRequestObject) (apigen.GameHotkeysResponseObject, error) {
	return responseFromPayload(ctx, request, a.service.GameHotkeys, func(value any) apigen.GameHotkeysResponseObject { return GameHotkeysJSONResponse{Payload: value} })
}

type GameSeeJSONResponse struct {
	Payload any
}

func (response GameSeeJSONResponse) VisitGameSeeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)

	return json.NewEncoder(w).Encode(response.Payload)
}

func (a *openAPIStrictAdapter) GameSee(ctx context.Context, request apigen.GameSeeRequestObject) (apigen.GameSeeResponseObject, error) {
	return responseFromPayload(ctx, request, a.service.GameSee, func(value any) apigen.GameSeeResponseObject { return GameSeeJSONResponse{Payload: value} })
}

type HealthcheckJSONResponse struct {
	Payload any
}

func (response HealthcheckJSONResponse) VisitHealthcheckResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)

	return json.NewEncoder(w).Encode(response.Payload)
}

func (a *openAPIStrictAdapter) Healthcheck(ctx context.Context, request apigen.HealthcheckRequestObject) (apigen.HealthcheckResponseObject, error) {
	return responseFromPayload(ctx, request, a.service.Healthcheck, func(value any) apigen.HealthcheckResponseObject { return HealthcheckJSONResponse{Payload: value} })
}

type PlayerColorsJSONResponse struct {
	Payload any
}

func (response PlayerColorsJSONResponse) VisitPlayerColorsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)

	return json.NewEncoder(w).Encode(response.Payload)
}

func (a *openAPIStrictAdapter) PlayerColors(ctx context.Context, request apigen.PlayerColorsRequestObject) (apigen.PlayerColorsResponseObject, error) {
	return responseFromPayload(ctx, request, a.service.PlayerColors, func(value any) apigen.PlayerColorsResponseObject { return PlayerColorsJSONResponse{Payload: value} })
}

type PlayersListJSONResponse struct {
	Payload any
}

func (response PlayersListJSONResponse) VisitPlayersListResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)

	return json.NewEncoder(w).Encode(response.Payload)
}

func (a *openAPIStrictAdapter) PlayersList(ctx context.Context, request apigen.PlayersListRequestObject) (apigen.PlayersListResponseObject, error) {
	return responseFromPayload(ctx, request, a.service.PlayersList, func(value any) apigen.PlayersListResponseObject { return PlayersListJSONResponse{Payload: value} })
}

type PlayersApmHistogramJSONResponse struct {
	Payload any
}

func (response PlayersApmHistogramJSONResponse) VisitPlayersApmHistogramResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)

	return json.NewEncoder(w).Encode(response.Payload)
}

func (a *openAPIStrictAdapter) PlayersApmHistogram(ctx context.Context, request apigen.PlayersApmHistogramRequestObject) (apigen.PlayersApmHistogramResponseObject, error) {
	return responseFromPayload(ctx, request, a.service.PlayersApmHistogram, func(value any) apigen.PlayersApmHistogramResponseObject {
		return PlayersApmHistogramJSONResponse{Payload: value}
	})
}

type PlayersUnitCadenceJSONResponse struct {
	Payload any
}

func (response PlayersUnitCadenceJSONResponse) VisitPlayersUnitCadenceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)

	return json.NewEncoder(w).Encode(response.Payload)
}

func (a *openAPIStrictAdapter) PlayersUnitCadence(ctx context.Context, request apigen.PlayersUnitCadenceRequestObject) (apigen.PlayersUnitCadenceResponseObject, error) {
	return responseFromPayload(ctx, request, a.service.PlayersUnitCadence, func(value any) apigen.PlayersUnitCadenceResponseObject {
		return PlayersUnitCadenceJSONResponse{Payload: value}
	})
}

type PlayersViewportMultitaskingJSONResponse struct {
	Payload any
}

func (response PlayersViewportMultitaskingJSONResponse) VisitPlayersViewportMultitaskingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)

	return json.NewEncoder(w).Encode(response.Payload)
}

func (a *openAPIStrictAdapter) PlayersViewportMultitasking(ctx context.Context, request apigen.PlayersViewportMultitaskingRequestObject) (apigen.PlayersViewportMultitaskingResponseObject, error) {
	return responseFromPayload(ctx, request, a.service.PlayersViewportMultitasking, func(value any) apigen.PlayersViewportMultitaskingResponseObject {
		return PlayersViewportMultitaskingJSONResponse{Payload: value}
	})
}

type PlayerDetailJSONResponse struct {
	Payload any
}

func (response PlayerDetailJSONResponse) VisitPlayerDetailResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)

	return json.NewEncoder(w).Encode(response.Payload)
}

func (a *openAPIStrictAdapter) PlayerDetail(ctx context.Context, request apigen.PlayerDetailRequestObject) (apigen.PlayerDetailResponseObject, error) {
	return responseFromPayload(ctx, request, a.service.PlayerDetail, func(value any) apigen.PlayerDetailResponseObject { return PlayerDetailJSONResponse{Payload: value} })
}

type PlayerChatSummaryJSONResponse struct {
	Payload any
}

func (response PlayerChatSummaryJSONResponse) VisitPlayerChatSummaryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)

	return json.NewEncoder(w).Encode(response.Payload)
}

func (a *openAPIStrictAdapter) PlayerChatSummary(ctx context.Context, request apigen.PlayerChatSummaryRequestObject) (apigen.PlayerChatSummaryResponseObject, error) {
	return responseFromPayload(ctx, request, a.service.PlayerChatSummary, func(value any) apigen.PlayerChatSummaryResponseObject {
		return PlayerChatSummaryJSONResponse{Payload: value}
	})
}

type PlayerHotkeySignatureJSONResponse struct {
	Payload any
}

func (response PlayerHotkeySignatureJSONResponse) VisitPlayerHotkeySignatureResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)

	return json.NewEncoder(w).Encode(response.Payload)
}

func (a *openAPIStrictAdapter) PlayerHotkeySignature(ctx context.Context, request apigen.PlayerHotkeySignatureRequestObject) (apigen.PlayerHotkeySignatureResponseObject, error) {
	return responseFromPayload(ctx, request, a.service.PlayerHotkeySignature, func(value any) apigen.PlayerHotkeySignatureResponseObject {
		return PlayerHotkeySignatureJSONResponse{Payload: value}
	})
}

type PlayerInsightJSONResponse struct {
	Payload any
}

func (response PlayerInsightJSONResponse) VisitPlayerInsightResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)

	return json.NewEncoder(w).Encode(response.Payload)
}

func (a *openAPIStrictAdapter) PlayerInsight(ctx context.Context, request apigen.PlayerInsightRequestObject) (apigen.PlayerInsightResponseObject, error) {
	return responseFromPayload(ctx, request, a.service.PlayerInsight, func(value any) apigen.PlayerInsightResponseObject { return PlayerInsightJSONResponse{Payload: value} })
}

type PlayerApmHistogramJSONResponse struct {
	Payload any
}

func (response PlayerApmHistogramJSONResponse) VisitPlayerApmHistogramResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)

	return json.NewEncoder(w).Encode(response.Payload)
}

func (a *openAPIStrictAdapter) PlayerApmHistogram(ctx context.Context, request apigen.PlayerApmHistogramRequestObject) (apigen.PlayerApmHistogramResponseObject, error) {
	return responseFromPayload(ctx, request, a.service.PlayerApmHistogram, func(value any) apigen.PlayerApmHistogramResponseObject {
		return PlayerApmHistogramJSONResponse{Payload: value}
	})
}

type PlayerUnitCadenceJSONResponse struct {
	Payload any
}

func (response PlayerUnitCadenceJSONResponse) VisitPlayerUnitCadenceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)

	return json.NewEncoder(w).Encode(response.Payload)
}

func (a *openAPIStrictAdapter) PlayerUnitCadence(ctx context.Context, request apigen.PlayerUnitCadenceRequestObject) (apigen.PlayerUnitCadenceResponseObject, error) {
	return responseFromPayload(ctx, request, a.service.PlayerUnitCadence, func(value any) apigen.PlayerUnitCadenceResponseObject {
		return PlayerUnitCadenceJSONResponse{Payload: value}
	})
}

type PlayerLastGamesJSONResponse struct {
	Payload any
}

func (response PlayerLastGamesJSONResponse) VisitPlayerLastGamesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)

	return json.NewEncoder(w).Encode(response.Payload)
}

func (a *openAPIStrictAdapter) PlayerLastGames(ctx context.Context, request apigen.PlayerLastGamesRequestObject) (apigen.PlayerLastGamesResponseObject, error) {
	return responseFromPayload(ctx, request, a.service.PlayerLastGames, func(value any) apigen.PlayerLastGamesResponseObject {
		return PlayerLastGamesJSONResponse{Payload: value}
	})
}

type ScrepColorsJSONResponse struct {
	Payload any
}

func (response ScrepColorsJSONResponse) VisitScrepColorsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)

	return json.NewEncoder(w).Encode(response.Payload)
}

func (a *openAPIStrictAdapter) ScrepColors(ctx context.Context, request apigen.ScrepColorsRequestObject) (apigen.ScrepColorsResponseObject, error) {
	return responseFromPayload(ctx, request, a.service.ScrepColors, func(value any) apigen.ScrepColorsResponseObject { return ScrepColorsJSONResponse{Payload: value} })
}
