package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

type method struct {
	Name     string
	ReqType  string
	RespType string
}

var methodRx = regexp.MustCompile(`^\s*([A-Za-z0-9_]+)\(ctx context\.Context, request ([A-Za-z0-9_]+)\) \(([A-Za-z0-9_]+), error\)\s*$`)

func main() {
	repoRoot, err := os.Getwd()
	if err != nil {
		fail(err)
	}

	apigenPath := filepath.Join(repoRoot, "internal/dashboard/apigen/server.gen.go")
	content, err := os.ReadFile(apigenPath)
	if err != nil {
		fail(err)
	}

	methods, err := parseStrictMethods(string(content))
	if err != nil {
		fail(err)
	}

	serviceOut := filepath.Join(repoRoot, "internal/dashboard/service/contracts_gen.go")
	if err := os.WriteFile(serviceOut, renderServiceContracts(methods), 0644); err != nil {
		fail(err)
	}

	adapterOut := filepath.Join(repoRoot, "internal/dashboard/openapi_handlers_gen.go")
	if err := os.WriteFile(adapterOut, renderStrictAdapter(methods), 0644); err != nil {
		fail(err)
	}
}

func parseStrictMethods(content string) ([]method, error) {
	const header = "type StrictServerInterface interface {"
	start := strings.Index(content, header)
	if start < 0 {
		return nil, fmt.Errorf("StrictServerInterface not found")
	}
	body := content[start+len(header):]
	end := strings.Index(body, "\n}")
	if end < 0 {
		return nil, fmt.Errorf("StrictServerInterface closing brace not found")
	}
	body = body[:end]

	out := []method{}
	for _, line := range strings.Split(body, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "//") {
			continue
		}
		m := methodRx.FindStringSubmatch(line)
		if len(m) != 4 {
			continue
		}
		out = append(out, method{Name: m[1], ReqType: m[2], RespType: m[3]})
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("no strict methods parsed")
	}
	return out, nil
}

func renderServiceContracts(methods []method) []byte {
	var b bytes.Buffer
	b.WriteString("package service\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n\n")
	b.WriteString("\t\"github.com/marianogappa/screpdb/internal/dashboard/apigen\"\n")
	b.WriteString(")\n\n")
	b.WriteString("// DashboardService is generated from apigen.StrictServerInterface.\n")
	b.WriteString("type DashboardService interface {\n")
	for _, m := range methods {
		b.WriteString(fmt.Sprintf("\t%s(ctx context.Context, request apigen.%s) (HandlerResult, error)\n", m.Name, m.ReqType))
	}
	b.WriteString("}\n")
	return mustFormat(b.Bytes())
}

func renderStrictAdapter(methods []method) []byte {
	var b bytes.Buffer
	b.WriteString("package dashboard\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"net/http\"\n\n")
	b.WriteString("\t\"github.com/marianogappa/screpdb/internal/dashboard/apigen\"\n")
	b.WriteString(")\n\n")
	b.WriteString("// Code generated by gen_openapi_bridge. DO NOT EDIT.\n")
	for _, m := range methods {
		if m.Name != "IngestLogs" {
			b.WriteString(fmt.Sprintf("type %sJSONResponse struct {\n\tPayload any\n}\n\n", m.Name))
			b.WriteString(fmt.Sprintf("func (response %sJSONResponse) Visit%sResponse(w http.ResponseWriter) error {\n", m.Name, m.Name))
			b.WriteString("\tw.Header().Set(\"Content-Type\", \"application/json\")\n")
			b.WriteString("\tw.WriteHeader(http.StatusOK)\n\n")
			b.WriteString("\treturn json.NewEncoder(w).Encode(response.Payload)\n")
			b.WriteString("}\n\n")
		}
		b.WriteString(fmt.Sprintf("func (a *openAPIStrictAdapter) %s(ctx context.Context, request apigen.%s) (apigen.%s, error) {\n", m.Name, m.ReqType, m.RespType))
		if m.Name == "IngestLogs" {
			b.WriteString(fmt.Sprintf("\treturn responseFromPayload(ctx, request, a.service.%s, func(_ any) apigen.%s { return apigen.IngestLogs101Response{} })\n", m.Name, m.RespType))
		} else {
			b.WriteString(fmt.Sprintf("\treturn responseFromPayload(ctx, request, a.service.%s, func(value any) apigen.%s { return %sJSONResponse{Payload: value} })\n", m.Name, m.RespType, m.Name))
		}
		b.WriteString("}\n\n")
	}
	return mustFormat(b.Bytes())
}

func mustFormat(src []byte) []byte {
	formatted, err := format.Source(src)
	if err != nil {
		fail(err)
	}
	return formatted
}

func fail(err error) {
	fmt.Fprintf(os.Stderr, "gen_openapi_bridge: %v\n", err)
	os.Exit(1)
}
