#!/usr/bin/env bash
# Regenerate the Homebrew formula (screpdb.rb) for a release.
#
# Usage: scripts/update-homebrew-formula.sh <version> <path-to-SHA256SUMS> <out-path>
#   <version>       release version, with or without a leading "v" (e.g. 1.3.0)
#   <SHA256SUMS>    the SHA256SUMS file produced by `make cross-binaries`
#   <out-path>      where to write the formula (e.g. Formula/screpdb.rb in the tap)
#
# Run by the release workflow after building binaries; can also be run locally.
# The formula ships the prebuilt release binaries directly: because `brew`
# fetches over curl (not a browser) it attaches no macOS quarantine xattr, so
# the binary just runs — no notarization required.
set -euo pipefail

VERSION="${1:?usage: update-homebrew-formula.sh <version> <SHA256SUMS> <out-path>}"
SUMS="${2:?usage: update-homebrew-formula.sh <version> <SHA256SUMS> <out-path>}"
OUT="${3:?usage: update-homebrew-formula.sh <version> <SHA256SUMS> <out-path>}"
VERSION="${VERSION#v}"

hash_for() {
  local name="$1" h
  h="$(awk -v n="$name" '$2 == n {print $1}' "$SUMS")"
  if [ -z "$h" ]; then
    echo "error: no checksum for '$name' in $SUMS" >&2
    exit 1
  fi
  printf '%s' "$h"
}

DARWIN_ARM64_HASH="$(hash_for screpdb-darwin-arm64)"
DARWIN_AMD64_HASH="$(hash_for screpdb-darwin-amd64)"
LINUX_ARM64_HASH="$(hash_for screpdb-linux-arm64)"
LINUX_AMD64_HASH="$(hash_for screpdb-linux-amd64)"

BASE="https://github.com/marianogappa/screpdb/releases/download/v${VERSION}"

cat > "$OUT" <<RUBY
# typed: false
# frozen_string_literal: true

# This file is auto-generated by scripts/update-homebrew-formula.sh on release.
class Screpdb < Formula
  desc "Advanced StarCraft: Brood War replay reporting tool (CLI + local dashboard)"
  homepage "https://github.com/marianogappa/screpdb"
  version "${VERSION}"
  license "MIT"

  on_macos do
    on_arm do
      url "${BASE}/screpdb-darwin-arm64"
      sha256 "${DARWIN_ARM64_HASH}"
    end
    on_intel do
      url "${BASE}/screpdb-darwin-amd64"
      sha256 "${DARWIN_AMD64_HASH}"
    end
  end

  on_linux do
    on_arm do
      url "${BASE}/screpdb-linux-arm64"
      sha256 "${LINUX_ARM64_HASH}"
    end
    on_intel do
      url "${BASE}/screpdb-linux-amd64"
      sha256 "${LINUX_AMD64_HASH}"
    end
  end

  def install
    bin.install Dir["screpdb-*"].first => "screpdb"
  end

  test do
    assert_match "screpdb", shell_output("#{bin}/screpdb --help 2>&1")
  end
end
RUBY

echo "Wrote $OUT (version ${VERSION})"
