// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dashdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Dashboard struct {
	ID          int64            `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type DashboardWidget struct {
	ID          int64            `json:"id"`
	DashboardID pgtype.Int8      `json:"dashboard_id"`
	WidgetOrder pgtype.Int8      `json:"widget_order"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Content     string           `json:"content"`
	Query       string           `json:"query"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type DashboardWidgetsPromptHistory struct {
	ID                int64            `json:"id"`
	DashboardID       pgtype.Int8      `json:"dashboard_id"`
	DashboardWidgetID pgtype.Int8      `json:"dashboard_widget_id"`
	Prompt            string           `json:"prompt"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
}
