// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dashdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Dashboard struct {
	Url         string           `json:"url"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type DashboardWidget struct {
	ID          int64            `json:"id"`
	DashboardID pgtype.Text      `json:"dashboard_id"`
	WidgetOrder pgtype.Int8      `json:"widget_order"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Config      []byte           `json:"config"`
	Query       string           `json:"query"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type DashboardWidgetPromptHistory struct {
	ID            int64            `json:"id"`
	WidgetID      int64            `json:"widget_id"`
	PromptHistory []byte           `json:"prompt_history"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}
