// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dashdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDashboard = `-- name: CreateDashboard :one
INSERT INTO dashboards (
  name, description
) VALUES (
  $1, $2
) RETURNING id, name, description, created_at
`

type CreateDashboardParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateDashboard(ctx context.Context, arg CreateDashboardParams) (Dashboard, error) {
	row := q.db.QueryRow(ctx, createDashboard, arg.Name, arg.Description)
	var i Dashboard
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createDashboardWidget = `-- name: CreateDashboardWidget :one
INSERT INTO dashboard_widgets (
  dashboard_id, widget_order, name, description, content, query
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, dashboard_id, widget_order, name, description, content, query, created_at, updated_at
`

type CreateDashboardWidgetParams struct {
	DashboardID pgtype.Int8 `json:"dashboard_id"`
	WidgetOrder pgtype.Int8 `json:"widget_order"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Content     string      `json:"content"`
	Query       string      `json:"query"`
}

func (q *Queries) CreateDashboardWidget(ctx context.Context, arg CreateDashboardWidgetParams) (DashboardWidget, error) {
	row := q.db.QueryRow(ctx, createDashboardWidget,
		arg.DashboardID,
		arg.WidgetOrder,
		arg.Name,
		arg.Description,
		arg.Content,
		arg.Query,
	)
	var i DashboardWidget
	err := row.Scan(
		&i.ID,
		&i.DashboardID,
		&i.WidgetOrder,
		&i.Name,
		&i.Description,
		&i.Content,
		&i.Query,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDashboardWidgetPromptHistory = `-- name: CreateDashboardWidgetPromptHistory :one
INSERT INTO dashboard_widgets_prompt_history (
  dashboard_id, dashboard_widget_id, prompt
) VALUES (
  $1, $2, $3
) RETURNING id, dashboard_id, dashboard_widget_id, prompt, created_at
`

type CreateDashboardWidgetPromptHistoryParams struct {
	DashboardID       pgtype.Int8 `json:"dashboard_id"`
	DashboardWidgetID pgtype.Int8 `json:"dashboard_widget_id"`
	Prompt            string      `json:"prompt"`
}

func (q *Queries) CreateDashboardWidgetPromptHistory(ctx context.Context, arg CreateDashboardWidgetPromptHistoryParams) (DashboardWidgetsPromptHistory, error) {
	row := q.db.QueryRow(ctx, createDashboardWidgetPromptHistory, arg.DashboardID, arg.DashboardWidgetID, arg.Prompt)
	var i DashboardWidgetsPromptHistory
	err := row.Scan(
		&i.ID,
		&i.DashboardID,
		&i.DashboardWidgetID,
		&i.Prompt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDashboard = `-- name: DeleteDashboard :exec
DELETE FROM dashboards
WHERE id = $1
`

func (q *Queries) DeleteDashboard(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDashboard, id)
	return err
}

const deleteDashboardWidget = `-- name: DeleteDashboardWidget :exec
DELETE FROM dashboards
WHERE id = $1
`

func (q *Queries) DeleteDashboardWidget(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDashboardWidget, id)
	return err
}

const deleteDashboardWidgetPromptHistoriesOfDashboard = `-- name: DeleteDashboardWidgetPromptHistoriesOfDashboard :exec
DELETE FROM dashboard_widgets_prompt_history
WHERE dashboard_id = $1
`

func (q *Queries) DeleteDashboardWidgetPromptHistoriesOfDashboard(ctx context.Context, dashboardID pgtype.Int8) error {
	_, err := q.db.Exec(ctx, deleteDashboardWidgetPromptHistoriesOfDashboard, dashboardID)
	return err
}

const deleteDashboardWidgetPromptHistory = `-- name: DeleteDashboardWidgetPromptHistory :exec
DELETE FROM dashboard_widgets_prompt_history
WHERE dashboard_widget_id = $1
`

func (q *Queries) DeleteDashboardWidgetPromptHistory(ctx context.Context, dashboardWidgetID pgtype.Int8) error {
	_, err := q.db.Exec(ctx, deleteDashboardWidgetPromptHistory, dashboardWidgetID)
	return err
}

const deleteDashboardWidgetsOfDashboard = `-- name: DeleteDashboardWidgetsOfDashboard :exec
DELETE FROM dashboard_widgets
WHERE dashboard_id = $1
`

func (q *Queries) DeleteDashboardWidgetsOfDashboard(ctx context.Context, dashboardID pgtype.Int8) error {
	_, err := q.db.Exec(ctx, deleteDashboardWidgetsOfDashboard, dashboardID)
	return err
}

const getDashboard = `-- name: GetDashboard :one
SELECT id, name, description, created_at FROM dashboards
WHERE id = $1
`

func (q *Queries) GetDashboard(ctx context.Context, id int64) (Dashboard, error) {
	row := q.db.QueryRow(ctx, getDashboard, id)
	var i Dashboard
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getDashboardWidget = `-- name: GetDashboardWidget :one
SELECT id, dashboard_id, widget_order, name, description, content, query, created_at, updated_at FROM dashboard_widgets
WHERE id = $1
`

func (q *Queries) GetDashboardWidget(ctx context.Context, id int64) (DashboardWidget, error) {
	row := q.db.QueryRow(ctx, getDashboardWidget, id)
	var i DashboardWidget
	err := row.Scan(
		&i.ID,
		&i.DashboardID,
		&i.WidgetOrder,
		&i.Name,
		&i.Description,
		&i.Content,
		&i.Query,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDashboardWidgetNextWidgetOrder = `-- name: GetDashboardWidgetNextWidgetOrder :one
SELECT MAX(widget_order)+1 next_widget_order FROM dashboard_widgets
WHERE dashboard_id = $1
`

func (q *Queries) GetDashboardWidgetNextWidgetOrder(ctx context.Context, dashboardID pgtype.Int8) (int32, error) {
	row := q.db.QueryRow(ctx, getDashboardWidgetNextWidgetOrder, dashboardID)
	var next_widget_order int32
	err := row.Scan(&next_widget_order)
	return next_widget_order, err
}

const listDashboardWidgetPromptHistory = `-- name: ListDashboardWidgetPromptHistory :many
SELECT id, dashboard_id, dashboard_widget_id, prompt, created_at FROM dashboard_widgets_prompt_history
WHERE dashboard_id = $1 AND dashboard_widget_id = $2
ORDER BY id
`

type ListDashboardWidgetPromptHistoryParams struct {
	DashboardID       pgtype.Int8 `json:"dashboard_id"`
	DashboardWidgetID pgtype.Int8 `json:"dashboard_widget_id"`
}

func (q *Queries) ListDashboardWidgetPromptHistory(ctx context.Context, arg ListDashboardWidgetPromptHistoryParams) ([]DashboardWidgetsPromptHistory, error) {
	rows, err := q.db.Query(ctx, listDashboardWidgetPromptHistory, arg.DashboardID, arg.DashboardWidgetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardWidgetsPromptHistory
	for rows.Next() {
		var i DashboardWidgetsPromptHistory
		if err := rows.Scan(
			&i.ID,
			&i.DashboardID,
			&i.DashboardWidgetID,
			&i.Prompt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDashboardWidgets = `-- name: ListDashboardWidgets :many
SELECT id, dashboard_id, widget_order, name, description, content, query, created_at, updated_at FROM dashboard_widgets
WHERE dashboard_id = $1
ORDER BY widget_order
`

func (q *Queries) ListDashboardWidgets(ctx context.Context, dashboardID pgtype.Int8) ([]DashboardWidget, error) {
	rows, err := q.db.Query(ctx, listDashboardWidgets, dashboardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardWidget
	for rows.Next() {
		var i DashboardWidget
		if err := rows.Scan(
			&i.ID,
			&i.DashboardID,
			&i.WidgetOrder,
			&i.Name,
			&i.Description,
			&i.Content,
			&i.Query,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDashboards = `-- name: ListDashboards :many
SELECT id, name, description, created_at FROM dashboards
ORDER BY name
`

func (q *Queries) ListDashboards(ctx context.Context) ([]Dashboard, error) {
	rows, err := q.db.Query(ctx, listDashboards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dashboard
	for rows.Next() {
		var i Dashboard
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDashboard = `-- name: UpdateDashboard :exec
UPDATE dashboards
  set name = $2,
  description = $3
WHERE id = $1
`

type UpdateDashboardParams struct {
	ID          int64       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateDashboard(ctx context.Context, arg UpdateDashboardParams) error {
	_, err := q.db.Exec(ctx, updateDashboard, arg.ID, arg.Name, arg.Description)
	return err
}

const updateDashboardWidget = `-- name: UpdateDashboardWidget :exec
UPDATE dashboard_widgets
  set name = $2,
  description = $3,
  content = $4,
  query = $5,
  widget_order = $6
WHERE id = $1
`

type UpdateDashboardWidgetParams struct {
	ID          int64       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Content     string      `json:"content"`
	Query       string      `json:"query"`
	WidgetOrder pgtype.Int8 `json:"widget_order"`
}

func (q *Queries) UpdateDashboardWidget(ctx context.Context, arg UpdateDashboardWidgetParams) error {
	_, err := q.db.Exec(ctx, updateDashboardWidget,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Content,
		arg.Query,
		arg.WidgetOrder,
	)
	return err
}
