// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dashdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDashboard = `-- name: CreateDashboard :one
INSERT INTO dashboards (
  url, name, description
) VALUES (
  $1, $2, $3
) RETURNING url, name, description, created_at, updated_at
`

type CreateDashboardParams struct {
	Url         string      `json:"url"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateDashboard(ctx context.Context, arg CreateDashboardParams) (Dashboard, error) {
	row := q.db.QueryRow(ctx, createDashboard, arg.Url, arg.Name, arg.Description)
	var i Dashboard
	err := row.Scan(
		&i.Url,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDashboardWidget = `-- name: CreateDashboardWidget :one
INSERT INTO dashboard_widgets (
  dashboard_id, widget_order, name, description, config, query
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, dashboard_id, widget_order, name, description, config, query, created_at, updated_at
`

type CreateDashboardWidgetParams struct {
	DashboardID pgtype.Text `json:"dashboard_id"`
	WidgetOrder pgtype.Int8 `json:"widget_order"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Config      []byte      `json:"config"`
	Query       string      `json:"query"`
}

func (q *Queries) CreateDashboardWidget(ctx context.Context, arg CreateDashboardWidgetParams) (DashboardWidget, error) {
	row := q.db.QueryRow(ctx, createDashboardWidget,
		arg.DashboardID,
		arg.WidgetOrder,
		arg.Name,
		arg.Description,
		arg.Config,
		arg.Query,
	)
	var i DashboardWidget
	err := row.Scan(
		&i.ID,
		&i.DashboardID,
		&i.WidgetOrder,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.Query,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDashboard = `-- name: DeleteDashboard :exec
DELETE FROM dashboards
WHERE url = $1
`

func (q *Queries) DeleteDashboard(ctx context.Context, url string) error {
	_, err := q.db.Exec(ctx, deleteDashboard, url)
	return err
}

const deleteDashboardWidget = `-- name: DeleteDashboardWidget :exec
DELETE FROM dashboard_widgets
WHERE id = $1
`

func (q *Queries) DeleteDashboardWidget(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDashboardWidget, id)
	return err
}

const deleteDashboardWidgetsOfDashboard = `-- name: DeleteDashboardWidgetsOfDashboard :exec
DELETE FROM dashboard_widgets
WHERE dashboard_id = $1
`

func (q *Queries) DeleteDashboardWidgetsOfDashboard(ctx context.Context, dashboardID pgtype.Text) error {
	_, err := q.db.Exec(ctx, deleteDashboardWidgetsOfDashboard, dashboardID)
	return err
}

const getDashboard = `-- name: GetDashboard :one
SELECT url, name, description, created_at, updated_at FROM dashboards
WHERE url = $1
`

func (q *Queries) GetDashboard(ctx context.Context, url string) (Dashboard, error) {
	row := q.db.QueryRow(ctx, getDashboard, url)
	var i Dashboard
	err := row.Scan(
		&i.Url,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDashboardWidget = `-- name: GetDashboardWidget :one
SELECT id, dashboard_id, widget_order, name, description, config, query, created_at, updated_at FROM dashboard_widgets
WHERE id = $1
`

func (q *Queries) GetDashboardWidget(ctx context.Context, id int64) (DashboardWidget, error) {
	row := q.db.QueryRow(ctx, getDashboardWidget, id)
	var i DashboardWidget
	err := row.Scan(
		&i.ID,
		&i.DashboardID,
		&i.WidgetOrder,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.Query,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDashboardWidgetNextWidgetOrder = `-- name: GetDashboardWidgetNextWidgetOrder :one
SELECT COALESCE(MAX(widget_order), 0)+1 next_widget_order FROM dashboard_widgets
WHERE dashboard_id = $1
`

func (q *Queries) GetDashboardWidgetNextWidgetOrder(ctx context.Context, dashboardID pgtype.Text) (int32, error) {
	row := q.db.QueryRow(ctx, getDashboardWidgetNextWidgetOrder, dashboardID)
	var next_widget_order int32
	err := row.Scan(&next_widget_order)
	return next_widget_order, err
}

const getDashboardWidgetPromptHistory = `-- name: GetDashboardWidgetPromptHistory :one
SELECT id, widget_id, prompt_history, created_at, updated_at FROM dashboard_widget_prompt_history
WHERE id = $1
`

func (q *Queries) GetDashboardWidgetPromptHistory(ctx context.Context, id int64) (DashboardWidgetPromptHistory, error) {
	row := q.db.QueryRow(ctx, getDashboardWidgetPromptHistory, id)
	var i DashboardWidgetPromptHistory
	err := row.Scan(
		&i.ID,
		&i.WidgetID,
		&i.PromptHistory,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDashboardWidgets = `-- name: ListDashboardWidgets :many
SELECT id, dashboard_id, widget_order, name, description, config, query, created_at, updated_at FROM dashboard_widgets
WHERE dashboard_id = $1
ORDER BY widget_order
`

func (q *Queries) ListDashboardWidgets(ctx context.Context, dashboardID pgtype.Text) ([]DashboardWidget, error) {
	rows, err := q.db.Query(ctx, listDashboardWidgets, dashboardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardWidget{}
	for rows.Next() {
		var i DashboardWidget
		if err := rows.Scan(
			&i.ID,
			&i.DashboardID,
			&i.WidgetOrder,
			&i.Name,
			&i.Description,
			&i.Config,
			&i.Query,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDashboards = `-- name: ListDashboards :many
SELECT url, name, description, created_at, updated_at FROM dashboards
ORDER BY name
`

func (q *Queries) ListDashboards(ctx context.Context) ([]Dashboard, error) {
	rows, err := q.db.Query(ctx, listDashboards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dashboard{}
	for rows.Next() {
		var i Dashboard
		if err := rows.Scan(
			&i.Url,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDashboard = `-- name: UpdateDashboard :exec
UPDATE dashboards
  set name = $2,
  description = $3
WHERE url = $1
`

type UpdateDashboardParams struct {
	Url         string      `json:"url"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateDashboard(ctx context.Context, arg UpdateDashboardParams) error {
	_, err := q.db.Exec(ctx, updateDashboard, arg.Url, arg.Name, arg.Description)
	return err
}

const updateDashboardWidget = `-- name: UpdateDashboardWidget :exec
UPDATE dashboard_widgets
  set name = $2,
  description = $3,
  config = $4,
  query = $5,
  widget_order = $6
WHERE id = $1
`

type UpdateDashboardWidgetParams struct {
	ID          int64       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Config      []byte      `json:"config"`
	Query       string      `json:"query"`
	WidgetOrder pgtype.Int8 `json:"widget_order"`
}

func (q *Queries) UpdateDashboardWidget(ctx context.Context, arg UpdateDashboardWidgetParams) error {
	_, err := q.db.Exec(ctx, updateDashboardWidget,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Config,
		arg.Query,
		arg.WidgetOrder,
	)
	return err
}

const upsertDashboardWidgetPromptHistory = `-- name: UpsertDashboardWidgetPromptHistory :exec
INSERT INTO dashboard_widget_prompt_history (widget_id, prompt_history, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (widget_id) DO UPDATE SET prompt_history = $2, updated_at = NOW()
`

type UpsertDashboardWidgetPromptHistoryParams struct {
	WidgetID      int64  `json:"widget_id"`
	PromptHistory []byte `json:"prompt_history"`
}

func (q *Queries) UpsertDashboardWidgetPromptHistory(ctx context.Context, arg UpsertDashboardWidgetPromptHistoryParams) error {
	_, err := q.db.Exec(ctx, upsertDashboardWidgetPromptHistory, arg.WidgetID, arg.PromptHistory)
	return err
}
