// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: aliases.sql

package sqlcgen

import (
	"context"
)

const DeletePlayerAliasByID = `-- name: DeletePlayerAliasByID :exec
DELETE FROM player_aliases
WHERE id = ?
`

func (q *Queries) DeletePlayerAliasByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeletePlayerAliasByID, id)
	return err
}

const ListPlayerAliases = `-- name: ListPlayerAliases :many
SELECT
  id,
  canonical_alias,
  battle_tag_normalized,
  battle_tag_raw,
  aurora_id,
  source,
  updated_at
FROM player_aliases
ORDER BY battle_tag_normalized ASC, source ASC, canonical_alias ASC
`

func (q *Queries) ListPlayerAliases(ctx context.Context) ([]PlayerAlias, error) {
	rows, err := q.db.QueryContext(ctx, ListPlayerAliases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlayerAlias{}
	for rows.Next() {
		var i PlayerAlias
		if err := rows.Scan(
			&i.ID,
			&i.CanonicalAlias,
			&i.BattleTagNormalized,
			&i.BattleTagRaw,
			&i.AuroraID,
			&i.Source,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpsertPlayerAlias = `-- name: UpsertPlayerAlias :exec
INSERT INTO player_aliases (
  canonical_alias,
  battle_tag_normalized,
  battle_tag_raw,
  aurora_id,
  source
) VALUES (?, ?, ?, ?, ?)
ON CONFLICT(source, battle_tag_normalized, canonical_alias) DO UPDATE SET
  battle_tag_raw = excluded.battle_tag_raw,
  aurora_id = excluded.aurora_id,
  updated_at = CURRENT_TIMESTAMP
`

type UpsertPlayerAliasParams struct {
	CanonicalAlias      string
	BattleTagNormalized string
	BattleTagRaw        string
	AuroraID            *int64
	Source              string
}

func (q *Queries) UpsertPlayerAlias(ctx context.Context, arg UpsertPlayerAliasParams) error {
	_, err := q.db.ExecContext(ctx, UpsertPlayerAlias,
		arg.CanonicalAlias,
		arg.BattleTagNormalized,
		arg.BattleTagRaw,
		arg.AuroraID,
		arg.Source,
	)
	return err
}
