// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bnet_profiles.sql

package sqlcgen

import (
	"context"
)

const GetBnetProfile = `-- name: GetBnetProfile :one
SELECT found, aurora_id, battle_tag, country_code, payload, fetched_at
FROM bnet_profiles
WHERE toon = ? AND gateway = ?
`

type GetBnetProfileParams struct {
	Toon    string
	Gateway int64
}

type GetBnetProfileRow struct {
	Found       bool
	AuroraID    int64
	BattleTag   string
	CountryCode string
	Payload     string
	FetchedAt   string
}

func (q *Queries) GetBnetProfile(ctx context.Context, arg GetBnetProfileParams) (GetBnetProfileRow, error) {
	row := q.db.QueryRowContext(ctx, GetBnetProfile, arg.Toon, arg.Gateway)
	var i GetBnetProfileRow
	err := row.Scan(
		&i.Found,
		&i.AuroraID,
		&i.BattleTag,
		&i.CountryCode,
		&i.Payload,
		&i.FetchedAt,
	)
	return i, err
}

const UpsertBnetProfile = `-- name: UpsertBnetProfile :exec
INSERT INTO bnet_profiles (toon, gateway, found, aurora_id, battle_tag, country_code, payload, fetched_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (toon, gateway) DO UPDATE SET
	found = excluded.found,
	aurora_id = excluded.aurora_id,
	battle_tag = excluded.battle_tag,
	country_code = excluded.country_code,
	payload = excluded.payload,
	fetched_at = excluded.fetched_at
`

type UpsertBnetProfileParams struct {
	Toon        string
	Gateway     int64
	Found       bool
	AuroraID    int64
	BattleTag   string
	CountryCode string
	Payload     string
	FetchedAt   string
}

func (q *Queries) UpsertBnetProfile(ctx context.Context, arg UpsertBnetProfileParams) error {
	_, err := q.db.ExecContext(ctx, UpsertBnetProfile,
		arg.Toon,
		arg.Gateway,
		arg.Found,
		arg.AuroraID,
		arg.BattleTag,
		arg.CountryCode,
		arg.Payload,
		arg.FetchedAt,
	)
	return err
}
