// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const CreateDashboard = `-- name: CreateDashboard :exec
INSERT INTO dashboards (url, name, description, replays_filter_sql)
VALUES (?, ?, ?, ?)
`

type CreateDashboardParams struct {
	Url              string
	Name             string
	Description      *string
	ReplaysFilterSql *string
}

func (q *Queries) CreateDashboard(ctx context.Context, arg CreateDashboardParams) error {
	_, err := q.db.ExecContext(ctx, CreateDashboard,
		arg.Url,
		arg.Name,
		arg.Description,
		arg.ReplaysFilterSql,
	)
	return err
}

const CreateDashboardWidget = `-- name: CreateDashboardWidget :execresult
INSERT INTO dashboard_widgets (dashboard_id, widget_order, name, description, config, query)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateDashboardWidgetParams struct {
	DashboardID *string
	WidgetOrder *int64
	Name        string
	Description *string
	Config      string
	Query       string
}

func (q *Queries) CreateDashboardWidget(ctx context.Context, arg CreateDashboardWidgetParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, CreateDashboardWidget,
		arg.DashboardID,
		arg.WidgetOrder,
		arg.Name,
		arg.Description,
		arg.Config,
		arg.Query,
	)
}

const DeleteDashboardByURL = `-- name: DeleteDashboardByURL :exec
DELETE FROM dashboards
WHERE url = ?
`

func (q *Queries) DeleteDashboardByURL(ctx context.Context, url string) error {
	_, err := q.db.ExecContext(ctx, DeleteDashboardByURL, url)
	return err
}

const DeleteDashboardWidget = `-- name: DeleteDashboardWidget :exec
DELETE FROM dashboard_widgets
WHERE id = ?
`

func (q *Queries) DeleteDashboardWidget(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeleteDashboardWidget, id)
	return err
}

const DeleteDashboardWidgetsByDashboardID = `-- name: DeleteDashboardWidgetsByDashboardID :exec
DELETE FROM dashboard_widgets
WHERE dashboard_id = ?
`

func (q *Queries) DeleteDashboardWidgetsByDashboardID(ctx context.Context, dashboardID *string) error {
	_, err := q.db.ExecContext(ctx, DeleteDashboardWidgetsByDashboardID, dashboardID)
	return err
}

const GetDashboardByURL = `-- name: GetDashboardByURL :one
SELECT url, name, description, replays_filter_sql, created_at
FROM dashboards
WHERE url = ?
`

type GetDashboardByURLRow struct {
	Url              string
	Name             string
	Description      *string
	ReplaysFilterSql *string
	CreatedAt        *string
}

func (q *Queries) GetDashboardByURL(ctx context.Context, url string) (GetDashboardByURLRow, error) {
	row := q.db.QueryRowContext(ctx, GetDashboardByURL, url)
	var i GetDashboardByURLRow
	err := row.Scan(
		&i.Url,
		&i.Name,
		&i.Description,
		&i.ReplaysFilterSql,
		&i.CreatedAt,
	)
	return i, err
}

const GetDashboardWidgetByID = `-- name: GetDashboardWidgetByID :one
SELECT id, dashboard_id, widget_order, name, description, config, query, created_at, updated_at
FROM dashboard_widgets
WHERE id = ?
`

func (q *Queries) GetDashboardWidgetByID(ctx context.Context, id int64) (DashboardWidget, error) {
	row := q.db.QueryRowContext(ctx, GetDashboardWidgetByID, id)
	var i DashboardWidget
	err := row.Scan(
		&i.ID,
		&i.DashboardID,
		&i.WidgetOrder,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.Query,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetDashboardWidgets = `-- name: GetDashboardWidgets :many
SELECT id, dashboard_id, widget_order, name, description, config, query, created_at, updated_at
FROM dashboard_widgets
WHERE dashboard_id = ?
ORDER BY widget_order ASC
`

func (q *Queries) GetDashboardWidgets(ctx context.Context, dashboardID *string) ([]DashboardWidget, error) {
	rows, err := q.db.QueryContext(ctx, GetDashboardWidgets, dashboardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardWidget{}
	for rows.Next() {
		var i DashboardWidget
		if err := rows.Scan(
			&i.ID,
			&i.DashboardID,
			&i.WidgetOrder,
			&i.Name,
			&i.Description,
			&i.Config,
			&i.Query,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetNextWidgetOrder = `-- name: GetNextWidgetOrder :one
SELECT COALESCE(MAX(widget_order), 0) + 1 AS next_widget_order
FROM dashboard_widgets
WHERE dashboard_id = ?
`

func (q *Queries) GetNextWidgetOrder(ctx context.Context, dashboardID *string) (int64, error) {
	row := q.db.QueryRowContext(ctx, GetNextWidgetOrder, dashboardID)
	var next_widget_order int64
	err := row.Scan(&next_widget_order)
	return next_widget_order, err
}

const ListDashboards = `-- name: ListDashboards :many
SELECT url, name, description, replays_filter_sql, created_at
FROM dashboards
ORDER BY name ASC
`

type ListDashboardsRow struct {
	Url              string
	Name             string
	Description      *string
	ReplaysFilterSql *string
	CreatedAt        *string
}

func (q *Queries) ListDashboards(ctx context.Context) ([]ListDashboardsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListDashboards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDashboardsRow{}
	for rows.Next() {
		var i ListDashboardsRow
		if err := rows.Scan(
			&i.Url,
			&i.Name,
			&i.Description,
			&i.ReplaysFilterSql,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
