// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard_model.sql

package sqlcgen

import (
	"context"
)

const GetDashboardWithVariablesByURL = `-- name: GetDashboardWithVariablesByURL :one
SELECT url, name, description, replays_filter_sql, variables, created_at
FROM dashboards
WHERE url = ?
`

func (q *Queries) GetDashboardWithVariablesByURL(ctx context.Context, url string) (Dashboard, error) {
	row := q.db.QueryRowContext(ctx, GetDashboardWithVariablesByURL, url)
	var i Dashboard
	err := row.Scan(
		&i.Url,
		&i.Name,
		&i.Description,
		&i.ReplaysFilterSql,
		&i.Variables,
		&i.CreatedAt,
	)
	return i, err
}

const UpdateDashboardVariables = `-- name: UpdateDashboardVariables :exec
UPDATE dashboards
SET variables = ?
WHERE url = ?
`

type UpdateDashboardVariablesParams struct {
	Variables *string
	Url       string
}

func (q *Queries) UpdateDashboardVariables(ctx context.Context, arg UpdateDashboardVariablesParams) error {
	_, err := q.db.ExecContext(ctx, UpdateDashboardVariables, arg.Variables, arg.Url)
	return err
}
