// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game_detail.sql

package sqlcgen

import (
	"context"
)

const GetPlayerOverviewSummary = `-- name: GetPlayerOverviewSummary :one
SELECT
  CAST(COALESCE(MIN(p.name), '') AS TEXT) AS player_name,
  COUNT(*) AS games_played,
  CAST(COALESCE(SUM(CASE WHEN p.is_winner = 1 THEN 1 ELSE 0 END), 0) AS INTEGER) AS wins,
  CAST(COALESCE(AVG(p.apm), 0) AS FLOAT) AS avg_apm,
  CAST(COALESCE(AVG(p.eapm), 0) AS FLOAT) AS avg_eapm
FROM players p
WHERE lower(trim(p.name)) = ? AND p.is_observer = 0 AND lower(trim(coalesce(p.type, ''))) = 'human'
`

type GetPlayerOverviewSummaryRow struct {
	PlayerName  string
	GamesPlayed int64
	Wins        int64
	AvgApm      float64
	AvgEapm     float64
}

func (q *Queries) GetPlayerOverviewSummary(ctx context.Context, name string) (GetPlayerOverviewSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, GetPlayerOverviewSummary, name)
	var i GetPlayerOverviewSummaryRow
	err := row.Scan(
		&i.PlayerName,
		&i.GamesPlayed,
		&i.Wins,
		&i.AvgApm,
		&i.AvgEapm,
	)
	return i, err
}

const GetReplaySummary = `-- name: GetReplaySummary :one
SELECT id, replay_date, file_name, file_path, file_checksum, map_name, duration_seconds, game_type
FROM replays
WHERE id = ?
`

type GetReplaySummaryRow struct {
	ID              int64
	ReplayDate      string
	FileName        string
	FilePath        string
	FileChecksum    string
	MapName         string
	DurationSeconds int64
	GameType        string
}

func (q *Queries) GetReplaySummary(ctx context.Context, id int64) (GetReplaySummaryRow, error) {
	row := q.db.QueryRowContext(ctx, GetReplaySummary, id)
	var i GetReplaySummaryRow
	err := row.Scan(
		&i.ID,
		&i.ReplayDate,
		&i.FileName,
		&i.FilePath,
		&i.FileChecksum,
		&i.MapName,
		&i.DurationSeconds,
		&i.GameType,
	)
	return i, err
}

const ListPlayerApmAggregates = `-- name: ListPlayerApmAggregates :many
SELECT
  lower(trim(p.name)) AS player_key,
  CAST(COALESCE(MIN(p.name), '') AS TEXT) AS player_name,
  CAST(COALESCE(AVG(CASE WHEN p.apm > 0 THEN p.apm END), 0) AS FLOAT) AS average_apm,
  COUNT(*) AS games_played
FROM players p
WHERE p.is_observer = 0 AND lower(trim(coalesce(p.type, ''))) = 'human'
GROUP BY lower(trim(p.name))
HAVING COUNT(*) >= ?
  AND COALESCE(AVG(CASE WHEN p.apm > 0 THEN p.apm END), 0) > 0
`

type ListPlayerApmAggregatesRow struct {
	PlayerKey   string
	PlayerName  string
	AverageApm  float64
	GamesPlayed int64
}

func (q *Queries) ListPlayerApmAggregates(ctx context.Context, dollar_1 interface{}) ([]ListPlayerApmAggregatesRow, error) {
	rows, err := q.db.QueryContext(ctx, ListPlayerApmAggregates, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerApmAggregatesRow{}
	for rows.Next() {
		var i ListPlayerApmAggregatesRow
		if err := rows.Scan(
			&i.PlayerKey,
			&i.PlayerName,
			&i.AverageApm,
			&i.GamesPlayed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListPlayerPatterns = `-- name: ListPlayerPatterns :many
SELECT
  player_id,
  pattern_name,
  CASE
    WHEN value_bool IS NOT NULL THEN CASE WHEN value_bool = 1 THEN 'true' ELSE 'false' END
    WHEN value_int IS NOT NULL THEN CAST(value_int AS TEXT)
    WHEN value_string IS NOT NULL THEN value_string
    WHEN value_timestamp IS NOT NULL THEN CAST(value_timestamp AS TEXT)
    ELSE ''
  END AS pattern_value
FROM detected_patterns_replay_player
WHERE replay_id = ?
ORDER BY player_id ASC, pattern_name ASC
`

type ListPlayerPatternsRow struct {
	PlayerID     int64
	PatternName  string
	PatternValue string
}

func (q *Queries) ListPlayerPatterns(ctx context.Context, replayID int64) ([]ListPlayerPatternsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListPlayerPatterns, replayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerPatternsRow{}
	for rows.Next() {
		var i ListPlayerPatternsRow
		if err := rows.Scan(&i.PlayerID, &i.PatternName, &i.PatternValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListPlayerRecentGames = `-- name: ListPlayerRecentGames :many
SELECT
  r.id,
  r.replay_date,
  r.file_name,
  r.map_name,
  r.duration_seconds,
  r.game_type,
  CAST(COALESCE((
    SELECT group_concat(name, ', ')
    FROM (
      SELECT p2.name AS name
      FROM players p2
      WHERE p2.replay_id = r.id AND p2.is_observer = 0 AND lower(trim(coalesce(p2.type, ''))) = 'human'
      ORDER BY p2.team ASC, p2.id ASC
    )
  ), '') AS TEXT) AS players_label,
  CAST(COALESCE((
    SELECT group_concat(p3.name, ', ')
    FROM players p3
    WHERE p3.replay_id = r.id AND p3.is_winner = 1 AND p3.is_observer = 0 AND lower(trim(coalesce(p3.type, ''))) = 'human'
  ), '') AS TEXT) AS winners_label
FROM replays r
JOIN players p ON p.replay_id = r.id
WHERE lower(trim(p.name)) = ? AND p.is_observer = 0 AND lower(trim(coalesce(p.type, ''))) = 'human'
ORDER BY r.replay_date DESC, r.id DESC
LIMIT 12
`

type ListPlayerRecentGamesRow struct {
	ID              int64
	ReplayDate      string
	FileName        string
	MapName         string
	DurationSeconds int64
	GameType        string
	PlayersLabel    string
	WinnersLabel    string
}

func (q *Queries) ListPlayerRecentGames(ctx context.Context, name string) ([]ListPlayerRecentGamesRow, error) {
	rows, err := q.db.QueryContext(ctx, ListPlayerRecentGames, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerRecentGamesRow{}
	for rows.Next() {
		var i ListPlayerRecentGamesRow
		if err := rows.Scan(
			&i.ID,
			&i.ReplayDate,
			&i.FileName,
			&i.MapName,
			&i.DurationSeconds,
			&i.GameType,
			&i.PlayersLabel,
			&i.WinnersLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListReplayEvents = `-- name: ListReplayEvents :many
SELECT
  re.event_type,
  re.seconds_from_game_start,
  re.source_player_id,
  COALESCE(sp.name, '') AS source_player_name,
  COALESCE(sp.color, '') AS source_player_color,
  re.target_player_id,
  COALESCE(tp.name, '') AS target_player_name,
  COALESCE(tp.color, '') AS target_player_color,
  re.location_base_type,
  re.location_base_oclock,
  re.location_natural_of_oclock,
  re.location_mineral_only,
  re.attack_unit_types
FROM replay_events re
LEFT JOIN players sp ON sp.id = re.source_player_id
LEFT JOIN players tp ON tp.id = re.target_player_id
WHERE re.replay_id = ?
ORDER BY re.seconds_from_game_start ASC, re.event_type ASC, re.id ASC
`

type ListReplayEventsRow struct {
	EventType               string
	SecondsFromGameStart    int64
	SourcePlayerID          *int64
	SourcePlayerName        string
	SourcePlayerColor       string
	TargetPlayerID          *int64
	TargetPlayerName        string
	TargetPlayerColor       string
	LocationBaseType        *string
	LocationBaseOclock      *int64
	LocationNaturalOfOclock *int64
	LocationMineralOnly     *bool
	AttackUnitTypes         *string
}

func (q *Queries) ListReplayEvents(ctx context.Context, replayID int64) ([]ListReplayEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListReplayEvents, replayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReplayEventsRow{}
	for rows.Next() {
		var i ListReplayEventsRow
		if err := rows.Scan(
			&i.EventType,
			&i.SecondsFromGameStart,
			&i.SourcePlayerID,
			&i.SourcePlayerName,
			&i.SourcePlayerColor,
			&i.TargetPlayerID,
			&i.TargetPlayerName,
			&i.TargetPlayerColor,
			&i.LocationBaseType,
			&i.LocationBaseOclock,
			&i.LocationNaturalOfOclock,
			&i.LocationMineralOnly,
			&i.AttackUnitTypes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListReplayPatterns = `-- name: ListReplayPatterns :many
SELECT
  pattern_name,
  CASE
    WHEN value_bool IS NOT NULL THEN CASE WHEN value_bool = 1 THEN 'true' ELSE 'false' END
    WHEN value_int IS NOT NULL THEN CAST(value_int AS TEXT)
    WHEN value_string IS NOT NULL THEN value_string
    WHEN value_timestamp IS NOT NULL THEN CAST(value_timestamp AS TEXT)
    ELSE ''
  END AS pattern_value
FROM detected_patterns_replay
WHERE replay_id = ?
ORDER BY pattern_name ASC
`

type ListReplayPatternsRow struct {
	PatternName  string
	PatternValue string
}

func (q *Queries) ListReplayPatterns(ctx context.Context, replayID int64) ([]ListReplayPatternsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListReplayPatterns, replayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReplayPatternsRow{}
	for rows.Next() {
		var i ListReplayPatternsRow
		if err := rows.Scan(&i.PatternName, &i.PatternValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListReplayPlayersForDetail = `-- name: ListReplayPlayersForDetail :many
SELECT
  p.id,
  p.name,
  COALESCE(p.color, '') AS color,
  p.race,
  p.team,
  p.is_winner,
  p.start_location_oclock,
  p.apm,
  p.eapm,
  COUNT(c.id) AS command_count,
  (
    SELECT COUNT(*)
    FROM commands_low_value clv
    WHERE clv.player_id = p.id
      AND clv.action_type = 'Hotkey'
      AND clv.hotkey_type IS NOT NULL
  ) AS hotkey_count,
  (
    SELECT COUNT(*)
    FROM commands_low_value clv
    WHERE clv.player_id = p.id
  ) AS low_value_command_count
FROM players p
LEFT JOIN commands c ON c.player_id = p.id
WHERE p.replay_id = ? AND p.is_observer = 0
GROUP BY p.id, p.name, p.color, p.race, p.team, p.is_winner, p.start_location_oclock, p.apm, p.eapm
ORDER BY p.team ASC, p.id ASC
`

type ListReplayPlayersForDetailRow struct {
	ID                   int64
	Name                 string
	Color                string
	Race                 string
	Team                 int64
	IsWinner             bool
	StartLocationOclock  *int64
	Apm                  int64
	Eapm                 int64
	CommandCount         int64
	HotkeyCount          int64
	LowValueCommandCount int64
}

func (q *Queries) ListReplayPlayersForDetail(ctx context.Context, replayID int64) ([]ListReplayPlayersForDetailRow, error) {
	rows, err := q.db.QueryContext(ctx, ListReplayPlayersForDetail, replayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReplayPlayersForDetailRow{}
	for rows.Next() {
		var i ListReplayPlayersForDetailRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.Race,
			&i.Team,
			&i.IsWinner,
			&i.StartLocationOclock,
			&i.Apm,
			&i.Eapm,
			&i.CommandCount,
			&i.HotkeyCount,
			&i.LowValueCommandCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
