// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game_detail_more.sql

package sqlcgen

import (
	"context"
)

const CountPlayerGames = `-- name: CountPlayerGames :one
SELECT COUNT(*) AS games_played
FROM players p
WHERE lower(trim(p.name)) = ? AND p.is_observer = 0 AND lower(trim(coalesce(p.type, ''))) = 'human'
`

func (q *Queries) CountPlayerGames(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountPlayerGames, name)
	var games_played int64
	err := row.Scan(&games_played)
	return games_played, err
}

const ListDelayCommandRows = `-- name: ListDelayCommandRows :many
SELECT
  p.replay_id,
  p.id,
  p.name,
  p.race,
  c.seconds_from_game_start,
  c.action_type,
  c.unit_type,
  c.unit_types
FROM players p
JOIN commands c
  ON c.replay_id = p.replay_id
  AND c.player_id = p.id
WHERE
  p.is_observer = 0
  AND lower(trim(coalesce(p.type, ''))) = 'human'
  AND c.action_type IN ('Build', 'Train', 'Unit Morph')
  AND c.seconds_from_game_start <= ?
ORDER BY p.replay_id ASC, p.id ASC, c.seconds_from_game_start ASC, c.id ASC
`

type ListDelayCommandRowsRow struct {
	ReplayID             int64
	ID                   int64
	Name                 string
	Race                 string
	SecondsFromGameStart int64
	ActionType           string
	UnitType             *string
	UnitTypes            *string
}

func (q *Queries) ListDelayCommandRows(ctx context.Context, secondsFromGameStart int64) ([]ListDelayCommandRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListDelayCommandRows, secondsFromGameStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDelayCommandRowsRow{}
	for rows.Next() {
		var i ListDelayCommandRowsRow
		if err := rows.Scan(
			&i.ReplayID,
			&i.ID,
			&i.Name,
			&i.Race,
			&i.SecondsFromGameStart,
			&i.ActionType,
			&i.UnitType,
			&i.UnitTypes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListDelayCommandRowsForPlayer = `-- name: ListDelayCommandRowsForPlayer :many
SELECT
  p.replay_id,
  p.id,
  p.name,
  p.race,
  c.seconds_from_game_start,
  c.action_type,
  c.unit_type,
  c.unit_types
FROM players p
JOIN commands c
  ON c.replay_id = p.replay_id
  AND c.player_id = p.id
WHERE
  p.is_observer = 0
  AND lower(trim(coalesce(p.type, ''))) = 'human'
  AND c.action_type IN ('Build', 'Train', 'Unit Morph')
  AND c.seconds_from_game_start <= ?
  AND lower(trim(p.name)) = ?
ORDER BY p.replay_id ASC, p.id ASC, c.seconds_from_game_start ASC, c.id ASC
`

type ListDelayCommandRowsForPlayerParams struct {
	SecondsFromGameStart int64
	Name                 string
}

type ListDelayCommandRowsForPlayerRow struct {
	ReplayID             int64
	ID                   int64
	Name                 string
	Race                 string
	SecondsFromGameStart int64
	ActionType           string
	UnitType             *string
	UnitTypes            *string
}

func (q *Queries) ListDelayCommandRowsForPlayer(ctx context.Context, arg ListDelayCommandRowsForPlayerParams) ([]ListDelayCommandRowsForPlayerRow, error) {
	rows, err := q.db.QueryContext(ctx, ListDelayCommandRowsForPlayer, arg.SecondsFromGameStart, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDelayCommandRowsForPlayerRow{}
	for rows.Next() {
		var i ListDelayCommandRowsForPlayerRow
		if err := rows.Scan(
			&i.ReplayID,
			&i.ID,
			&i.Name,
			&i.Race,
			&i.SecondsFromGameStart,
			&i.ActionType,
			&i.UnitType,
			&i.UnitTypes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListRacePatterns = `-- name: ListRacePatterns :many
SELECT p.race, re.event_type AS pattern_name, COUNT(DISTINCT re.replay_id) AS replay_count
FROM replay_events re
JOIN players p ON p.id = re.source_player_id
WHERE lower(trim(p.name)) = ?
  AND p.is_observer = 0
  AND lower(trim(coalesce(p.type, ''))) = 'human'
  AND re.event_kind = 'marker'
  AND re.event_type NOT IN ('used_hotkey_groups', 'viewport_multitasking')
GROUP BY p.race, re.event_type
`

type ListRacePatternsRow struct {
	Race        string
	PatternName string
	ReplayCount int64
}

func (q *Queries) ListRacePatterns(ctx context.Context, name string) ([]ListRacePatternsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListRacePatterns, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRacePatternsRow{}
	for rows.Next() {
		var i ListRacePatternsRow
		if err := rows.Scan(&i.Race, &i.PatternName, &i.ReplayCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListRaceSections = `-- name: ListRaceSections :many
SELECT p.race, COUNT(*) AS game_count, CAST(COALESCE(SUM(CASE WHEN p.is_winner = 1 THEN 1 ELSE 0 END), 0) AS INTEGER) AS wins
FROM players p
WHERE lower(trim(p.name)) = ? AND p.is_observer = 0 AND lower(trim(coalesce(p.type, ''))) = 'human'
GROUP BY p.race
ORDER BY game_count DESC, p.race ASC
`

type ListRaceSectionsRow struct {
	Race      string
	GameCount int64
	Wins      int64
}

func (q *Queries) ListRaceSections(ctx context.Context, name string) ([]ListRaceSectionsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListRaceSections, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRaceSectionsRow{}
	for rows.Next() {
		var i ListRaceSectionsRow
		if err := rows.Scan(&i.Race, &i.GameCount, &i.Wins); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTopActionTypes = `-- name: ListTopActionTypes :many
SELECT c.action_type, COUNT(*) AS n
FROM commands c
WHERE c.player_id = ?
GROUP BY c.action_type
ORDER BY n DESC
LIMIT ?
`

type ListTopActionTypesParams struct {
	PlayerID int64
	Limit    int64
}

type ListTopActionTypesRow struct {
	ActionType string
	N          int64
}

func (q *Queries) ListTopActionTypes(ctx context.Context, arg ListTopActionTypesParams) ([]ListTopActionTypesRow, error) {
	rows, err := q.db.QueryContext(ctx, ListTopActionTypes, arg.PlayerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopActionTypesRow{}
	for rows.Next() {
		var i ListTopActionTypesRow
		if err := rows.Scan(&i.ActionType, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
