// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: global_replay_filter.sql

package sqlcgen

import (
	"context"
)

const GetGlobalReplayFilterConfigRaw = `-- name: GetGlobalReplayFilterConfigRaw :one
SELECT
  game_type,
  included_players,
  excluded_players,
  game_types_mode,
  game_types,
  exclude_short_games,
  exclude_computers,
  map_kind_filter_mode,
  map_kinds,
  player_filter_mode,
  players,
  compiled_replays_filter_sql
FROM settings
WHERE config_key = ?
`

type GetGlobalReplayFilterConfigRawRow struct {
	GameType                 string
	IncludedPlayers          string
	ExcludedPlayers          string
	GameTypesMode            string
	GameTypes                string
	ExcludeShortGames        bool
	ExcludeComputers         bool
	MapKindFilterMode        string
	MapKinds                 string
	PlayerFilterMode         string
	Players                  string
	CompiledReplaysFilterSql *string
}

func (q *Queries) GetGlobalReplayFilterConfigRaw(ctx context.Context, configKey string) (GetGlobalReplayFilterConfigRawRow, error) {
	row := q.db.QueryRowContext(ctx, GetGlobalReplayFilterConfigRaw, configKey)
	var i GetGlobalReplayFilterConfigRawRow
	err := row.Scan(
		&i.GameType,
		&i.IncludedPlayers,
		&i.ExcludedPlayers,
		&i.GameTypesMode,
		&i.GameTypes,
		&i.ExcludeShortGames,
		&i.ExcludeComputers,
		&i.MapKindFilterMode,
		&i.MapKinds,
		&i.PlayerFilterMode,
		&i.Players,
		&i.CompiledReplaysFilterSql,
	)
	return i, err
}

const ListGlobalReplayFilterPlayerOptions = `-- name: ListGlobalReplayFilterPlayerOptions :many
SELECT CAST(MIN(name) AS TEXT) AS label, COUNT(*) AS games
FROM players
WHERE is_observer = 0
GROUP BY lower(trim(name))
ORDER BY games DESC, label ASC
`

type ListGlobalReplayFilterPlayerOptionsRow struct {
	Label string
	Games int64
}

func (q *Queries) ListGlobalReplayFilterPlayerOptions(ctx context.Context) ([]ListGlobalReplayFilterPlayerOptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListGlobalReplayFilterPlayerOptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGlobalReplayFilterPlayerOptionsRow{}
	for rows.Next() {
		var i ListGlobalReplayFilterPlayerOptionsRow
		if err := rows.Scan(&i.Label, &i.Games); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateGlobalReplayFilterConfigRaw = `-- name: UpdateGlobalReplayFilterConfigRaw :exec
UPDATE settings
SET
  game_type = ?,
  included_maps = '[]',
  excluded_maps = '[]',
  included_players = '[]',
  excluded_players = '[]',
  game_types_mode = ?,
  game_types = ?,
  exclude_short_games = ?,
  exclude_computers = ?,
  map_kind_filter_mode = ?,
  map_kinds = ?,
  player_filter_mode = ?,
  players = ?,
  compiled_replays_filter_sql = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE config_key = ?
`

type UpdateGlobalReplayFilterConfigRawParams struct {
	GameType                 string
	GameTypesMode            string
	GameTypes                string
	ExcludeShortGames        bool
	ExcludeComputers         bool
	MapKindFilterMode        string
	MapKinds                 string
	PlayerFilterMode         string
	Players                  string
	CompiledReplaysFilterSql *string
	ConfigKey                string
}

func (q *Queries) UpdateGlobalReplayFilterConfigRaw(ctx context.Context, arg UpdateGlobalReplayFilterConfigRawParams) error {
	_, err := q.db.ExecContext(ctx, UpdateGlobalReplayFilterConfigRaw,
		arg.GameType,
		arg.GameTypesMode,
		arg.GameTypes,
		arg.ExcludeShortGames,
		arg.ExcludeComputers,
		arg.MapKindFilterMode,
		arg.MapKinds,
		arg.PlayerFilterMode,
		arg.Players,
		arg.CompiledReplaysFilterSql,
		arg.ConfigKey,
	)
	return err
}
