// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: global_replay_filter.sql

package sqlcgen

import (
	"context"
)

const GetGlobalReplayFilterConfigRaw = `-- name: GetGlobalReplayFilterConfigRaw :one
SELECT
  game_type,
  included_players,
  excluded_players,
  game_types_mode,
  game_types,
  exclude_short_games,
  exclude_computers,
  map_kind_filter_mode,
  map_kinds,
  player_filter_mode,
  players,
  compiled_replays_filter_sql
FROM settings
WHERE config_key = ?
`

type GetGlobalReplayFilterConfigRawRow struct {
	GameType                 string
	IncludedPlayers          string
	ExcludedPlayers          string
	GameTypesMode            string
	GameTypes                string
	ExcludeShortGames        bool
	ExcludeComputers         bool
	MapKindFilterMode        string
	MapKinds                 string
	PlayerFilterMode         string
	Players                  string
	CompiledReplaysFilterSql *string
}

func (q *Queries) GetGlobalReplayFilterConfigRaw(ctx context.Context, configKey string) (GetGlobalReplayFilterConfigRawRow, error) {
	row := q.db.QueryRowContext(ctx, GetGlobalReplayFilterConfigRaw, configKey)
	var i GetGlobalReplayFilterConfigRawRow
	err := row.Scan(
		&i.GameType,
		&i.IncludedPlayers,
		&i.ExcludedPlayers,
		&i.GameTypesMode,
		&i.GameTypes,
		&i.ExcludeShortGames,
		&i.ExcludeComputers,
		&i.MapKindFilterMode,
		&i.MapKinds,
		&i.PlayerFilterMode,
		&i.Players,
		&i.CompiledReplaysFilterSql,
	)
	return i, err
}

const UpdateGlobalReplayFilterConfigRaw = `-- name: UpdateGlobalReplayFilterConfigRaw :exec
UPDATE settings
SET
  game_type = ?,
  included_maps = '[]',
  excluded_maps = '[]',
  included_players = '[]',
  excluded_players = '[]',
  game_types_mode = ?,
  game_types = ?,
  exclude_short_games = ?,
  exclude_computers = ?,
  map_kind_filter_mode = ?,
  map_kinds = ?,
  player_filter_mode = ?,
  players = ?,
  compiled_replays_filter_sql = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE config_key = ?
`

type UpdateGlobalReplayFilterConfigRawParams struct {
	GameType                 string
	GameTypesMode            string
	GameTypes                string
	ExcludeShortGames        bool
	ExcludeComputers         bool
	MapKindFilterMode        string
	MapKinds                 string
	PlayerFilterMode         string
	Players                  string
	CompiledReplaysFilterSql *string
	ConfigKey                string
}

func (q *Queries) UpdateGlobalReplayFilterConfigRaw(ctx context.Context, arg UpdateGlobalReplayFilterConfigRawParams) error {
	_, err := q.db.ExecContext(ctx, UpdateGlobalReplayFilterConfigRaw,
		arg.GameType,
		arg.GameTypesMode,
		arg.GameTypes,
		arg.ExcludeShortGames,
		arg.ExcludeComputers,
		arg.MapKindFilterMode,
		arg.MapKinds,
		arg.PlayerFilterMode,
		arg.Players,
		arg.CompiledReplaysFilterSql,
		arg.ConfigKey,
	)
	return err
}
