// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hotkeys.sql

package sqlcgen

import (
	"context"
)

const CountPlayerBnetGames = `-- name: CountPlayerBnetGames :one
SELECT COUNT(*)
FROM replays r
JOIN players p ON p.replay_id = r.id
WHERE lower(trim(p.name)) = ?
  AND p.is_observer = 0
  AND r.game_source = 'AssumedBattleNet'
`

// Whether (and how much) a player appears in Battle.net-sourced replays; the
// player page shows its Battle.net section only when this is non-zero.
func (q *Queries) CountPlayerBnetGames(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountPlayerBnetGames, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetReplayPlayerHotkeyStream = `-- name: GetReplayPlayerHotkeyStream :one
SELECT
  p.id,
  p.name,
  p.race,
  p.slot_id,
  p.hotkey_stream
FROM players p
WHERE p.replay_id = ? AND p.id = ?
`

type GetReplayPlayerHotkeyStreamParams struct {
	ReplayID int64
	ID       int64
}

type GetReplayPlayerHotkeyStreamRow struct {
	ID           int64
	Name         string
	Race         string
	SlotID       int64
	HotkeyStream []byte
}

// One player's stream within one replay (hotkey map composite).
func (q *Queries) GetReplayPlayerHotkeyStream(ctx context.Context, arg GetReplayPlayerHotkeyStreamParams) (GetReplayPlayerHotkeyStreamRow, error) {
	row := q.db.QueryRowContext(ctx, GetReplayPlayerHotkeyStream, arg.ReplayID, arg.ID)
	var i GetReplayPlayerHotkeyStreamRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Race,
		&i.SlotID,
		&i.HotkeyStream,
	)
	return i, err
}

const ListPlayerHotkeyStreamsByKey = `-- name: ListPlayerHotkeyStreamsByKey :many
SELECT
  p.name,
  p.race,
  p.hotkey_stream,
  r.duration_seconds
FROM players p
JOIN replays r ON r.id = p.replay_id
WHERE lower(trim(p.name)) = ?
  AND p.hotkey_stream IS NOT NULL
  AND p.is_observer = 0
  AND r.duration_seconds >= 360
ORDER BY r.replay_date DESC
LIMIT 120
`

type ListPlayerHotkeyStreamsByKeyRow struct {
	Name            string
	Race            string
	HotkeyStream    []byte
	DurationSeconds int64
}

// All of a player's stored hotkey streams, newest first, for the hotkey
// signature aggregation. Race comes per game: a Random player contributes
// games under each actual race. Short games carry no phase signal.
func (q *Queries) ListPlayerHotkeyStreamsByKey(ctx context.Context, name string) ([]ListPlayerHotkeyStreamsByKeyRow, error) {
	rows, err := q.db.QueryContext(ctx, ListPlayerHotkeyStreamsByKey, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerHotkeyStreamsByKeyRow{}
	for rows.Next() {
		var i ListPlayerHotkeyStreamsByKeyRow
		if err := rows.Scan(
			&i.Name,
			&i.Race,
			&i.HotkeyStream,
			&i.DurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListReplayPlayerHotkeyStreams = `-- name: ListReplayPlayerHotkeyStreams :many
SELECT
  p.id,
  p.name,
  p.race,
  p.team,
  p.hotkey_stream
FROM players p
WHERE p.replay_id = ?
  AND p.is_observer = 0
  AND lower(trim(coalesce(p.type, ''))) = 'human'
ORDER BY p.team ASC, p.id ASC
`

type ListReplayPlayerHotkeyStreamsRow struct {
	ID           int64
	Name         string
	Race         string
	Team         int64
	HotkeyStream []byte
}

// Per-player encoded hotkey streams for one game (hotkey timeline tab).
// The blob is the internal/hotkeystream wire format; NULL when the player
// issued no hotkey commands.
func (q *Queries) ListReplayPlayerHotkeyStreams(ctx context.Context, replayID int64) ([]ListReplayPlayerHotkeyStreamsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListReplayPlayerHotkeyStreams, replayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReplayPlayerHotkeyStreamsRow{}
	for rows.Next() {
		var i ListReplayPlayerHotkeyStreamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Race,
			&i.Team,
			&i.HotkeyStream,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
