// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

type Command struct {
	ID                   int64
	ReplayID             int64
	PlayerID             int64
	Frame                int64
	SecondsFromGameStart int64
	ActionType           string
	IsQueued             *bool
	UnitType             *string
	UnitTypes            *string
	TechName             *string
	UpgradeName          *string
	HotkeyType           *string
	ChatMessage          *string
}

type CommandsLowValue struct {
	ID                   int64
	ReplayID             int64
	PlayerID             int64
	SecondsFromGameStart int64
	ActionType           string
	IsQueued             *bool
	UnitType             *string
	UnitTypes            *string
	TechName             *string
	UpgradeName          *string
	HotkeyType           *string
	ChatMessage          *string
}

type Dashboard struct {
	Url              string
	Name             string
	Description      *string
	ReplaysFilterSql *string
	Variables        *string
	CreatedAt        *string
}

type DashboardWidget struct {
	ID          int64
	DashboardID *string
	WidgetOrder *int64
	Name        string
	Description *string
	Config      string
	Query       string
	CreatedAt   *string
	UpdatedAt   *string
}

type MarkerAlgorithmState struct {
	ReplayID         int64
	AlgorithmVersion int64
	DetectedAt       string
}

type Player struct {
	ID                  int64
	ReplayID            int64
	Name                string
	Color               string
	Race                string
	Type                string
	Team                int64
	IsObserver          bool
	Apm                 int64
	Eapm                int64
	IsWinner            bool
	StartLocationOclock *int64
}

type PlayerAlias struct {
	ID                  int64
	CanonicalAlias      string
	BattleTagNormalized string
	BattleTagRaw        string
	AuroraID            *int64
	Source              string
	UpdatedAt           string
}

type Replay struct {
	ID              int64
	FilePath        string
	FileChecksum    string
	FileName        string
	ReplayDate      string
	MapName         string
	MapKind         string
	DurationSeconds int64
	GameType        string
	Matchup         string
}

type ReplayEvent struct {
	ID                      int64
	ReplayID                int64
	SecondsFromGameStart    int64
	EventKind               string
	EventType               string
	LocationBaseType        *string
	LocationBaseOclock      *int64
	LocationNaturalOfOclock *int64
	LocationMineralOnly     *bool
	SourcePlayerID          *int64
	TargetPlayerID          *int64
	AttackUnitTypes         *string
	AttackCastCounts        *string
	Payload                 *string
}

type Setting struct {
	ConfigKey                string
	GameType                 string
	ExcludeShortGames        bool
	ExcludeComputers         bool
	IncludedMaps             string
	ExcludedMaps             string
	IncludedPlayers          string
	ExcludedPlayers          string
	IngestInputDir           string
	GameTypesMode            string
	GameTypes                string
	MapFilterMode            string
	Maps                     string
	MapKindFilterMode        string
	MapKinds                 string
	PlayerFilterMode         string
	Players                  string
	CompiledReplaysFilterSql *string
	UpdatedAt                *string
}
