// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player_insight_static.sql

package sqlcgen

import (
	"context"
)

const ListCommonBehaviours = `-- name: ListCommonBehaviours :many
SELECT re.event_type AS pattern_name, COUNT(DISTINCT re.replay_id) AS replay_count
FROM replay_events re
JOIN players p ON p.id = re.source_player_id
WHERE lower(trim(p.name)) = ?
  AND p.is_observer = 0
  AND re.event_kind = 'marker'
  AND re.event_type NOT IN ('used_hotkey_groups', 'viewport_multitasking')
GROUP BY re.event_type
`

type ListCommonBehavioursRow struct {
	PatternName string
	ReplayCount int64
}

func (q *Queries) ListCommonBehaviours(ctx context.Context, name string) ([]ListCommonBehavioursRow, error) {
	rows, err := q.db.QueryContext(ctx, ListCommonBehaviours, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommonBehavioursRow{}
	for rows.Next() {
		var i ListCommonBehavioursRow
		if err := rows.Scan(&i.PatternName, &i.ReplayCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
