// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player_insight_static.sql

package sqlcgen

import (
	"context"
)

const GetOutlierPlayerSummary = `-- name: GetOutlierPlayerSummary :one
SELECT CAST(MIN(p.name) AS TEXT) AS name, COUNT(*) AS count
FROM players p
WHERE lower(trim(p.name)) = ? AND p.is_observer = 0 AND lower(trim(coalesce(p.type, ''))) = 'human'
`

type GetOutlierPlayerSummaryRow struct {
	Name  string
	Count int64
}

func (q *Queries) GetOutlierPlayerSummary(ctx context.Context, name string) (GetOutlierPlayerSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, GetOutlierPlayerSummary, name)
	var i GetOutlierPlayerSummaryRow
	err := row.Scan(&i.Name, &i.Count)
	return i, err
}

const ListCommonBehaviours = `-- name: ListCommonBehaviours :many
SELECT re.event_type AS pattern_name, COUNT(DISTINCT re.replay_id) AS replay_count
FROM replay_events re
JOIN players p ON p.id = re.source_player_id
WHERE lower(trim(p.name)) = ?
  AND p.is_observer = 0
  AND re.event_kind = 'marker'
  AND re.event_type NOT IN ('used_hotkey_groups', 'viewport_multitasking')
GROUP BY re.event_type
`

type ListCommonBehavioursRow struct {
	PatternName string
	ReplayCount int64
}

func (q *Queries) ListCommonBehaviours(ctx context.Context, name string) ([]ListCommonBehavioursRow, error) {
	rows, err := q.db.QueryContext(ctx, ListCommonBehaviours, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommonBehavioursRow{}
	for rows.Next() {
		var i ListCommonBehavioursRow
		if err := rows.Scan(&i.PatternName, &i.ReplayCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListPlayerGamesByRace = `-- name: ListPlayerGamesByRace :many
SELECT p.race, COUNT(*) AS games
FROM players p
WHERE lower(trim(p.name)) = ? AND p.is_observer = 0 AND lower(trim(coalesce(p.type, ''))) = 'human'
GROUP BY p.race
`

type ListPlayerGamesByRaceRow struct {
	Race  string
	Games int64
}

func (q *Queries) ListPlayerGamesByRace(ctx context.Context, name string) ([]ListPlayerGamesByRaceRow, error) {
	rows, err := q.db.QueryContext(ctx, ListPlayerGamesByRace, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerGamesByRaceRow{}
	for rows.Next() {
		var i ListPlayerGamesByRaceRow
		if err := rows.Scan(&i.Race, &i.Games); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListPopulationDistinctPlayersByRace = `-- name: ListPopulationDistinctPlayersByRace :many
SELECT p.race, CAST(COUNT(*) AS FLOAT) AS value
FROM (
  SELECT lower(trim(name)) AS player_key, race
  FROM players
  WHERE is_observer = 0 AND lower(trim(coalesce(type, ''))) = 'human'
  GROUP BY lower(trim(name)), race
) p
GROUP BY p.race
`

type ListPopulationDistinctPlayersByRaceRow struct {
	Race  string
	Value float64
}

func (q *Queries) ListPopulationDistinctPlayersByRace(ctx context.Context) ([]ListPopulationDistinctPlayersByRaceRow, error) {
	rows, err := q.db.QueryContext(ctx, ListPopulationDistinctPlayersByRace)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPopulationDistinctPlayersByRaceRow{}
	for rows.Next() {
		var i ListPopulationDistinctPlayersByRaceRow
		if err := rows.Scan(&i.Race, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListPopulationGamesByRace = `-- name: ListPopulationGamesByRace :many
SELECT p.race, COUNT(*) AS games
FROM players p
WHERE p.is_observer = 0 AND lower(trim(coalesce(p.type, ''))) = 'human'
GROUP BY p.race
`

type ListPopulationGamesByRaceRow struct {
	Race  string
	Games int64
}

func (q *Queries) ListPopulationGamesByRace(ctx context.Context) ([]ListPopulationGamesByRaceRow, error) {
	rows, err := q.db.QueryContext(ctx, ListPopulationGamesByRace)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPopulationGamesByRaceRow{}
	for rows.Next() {
		var i ListPopulationGamesByRaceRow
		if err := rows.Scan(&i.Race, &i.Games); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
