// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player_insight_aux.sql

package sqlcgen

import (
	"context"
)

const CountCarrierGamesByPlayer = `-- name: CountCarrierGamesByPlayer :one
SELECT COUNT(DISTINCT p.replay_id) AS count
FROM detected_patterns_replay_player dp
JOIN players p ON p.id = dp.player_id
WHERE lower(trim(p.name)) = ?
  AND p.is_observer = 0
  AND dp.pattern_name = 'Carriers'
  AND dp.value_bool = 1
`

func (q *Queries) CountCarrierGamesByPlayer(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountCarrierGamesByPlayer, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountDistinctPlayers = `-- name: CountDistinctPlayers :one
SELECT CAST(COUNT(*) AS FLOAT) AS total
FROM (
  SELECT lower(trim(name)) AS player_key
  FROM players
  WHERE is_observer = 0
  GROUP BY lower(trim(name))
)
`

func (q *Queries) CountDistinctPlayers(ctx context.Context) (float64, error) {
	row := q.db.QueryRowContext(ctx, CountDistinctPlayers)
	var total float64
	err := row.Scan(&total)
	return total, err
}

const CountDistinctPlayersByRace = `-- name: CountDistinctPlayersByRace :one
SELECT CAST(COUNT(*) AS FLOAT) AS total
FROM (
  SELECT lower(trim(name)) AS player_key
  FROM players
  WHERE is_observer = 0
    AND race = ?
  GROUP BY lower(trim(name))
)
`

func (q *Queries) CountDistinctPlayersByRace(ctx context.Context, race string) (float64, error) {
	row := q.db.QueryRowContext(ctx, CountDistinctPlayersByRace, race)
	var total float64
	err := row.Scan(&total)
	return total, err
}

const CountQueuedGamesByPlayer = `-- name: CountQueuedGamesByPlayer :one
SELECT COUNT(DISTINCT p.id) AS count
FROM players p
JOIN commands c ON c.player_id = p.id
WHERE lower(trim(p.name)) = ?
  AND p.is_observer = 0
  AND c.is_queued = 1
`

func (q *Queries) CountQueuedGamesByPlayer(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountQueuedGamesByPlayer, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetPlayerNameByKey = `-- name: GetPlayerNameByKey :one
SELECT CAST(COALESCE(MIN(name), '') AS TEXT) AS player_name
FROM players
WHERE lower(trim(name)) = ?
  AND is_observer = 0
  AND lower(trim(coalesce(type, ''))) = 'human'
`

func (q *Queries) GetPlayerNameByKey(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRowContext(ctx, GetPlayerNameByKey, name)
	var player_name string
	err := row.Scan(&player_name)
	return player_name, err
}

const ListExpansionEvents = `-- name: ListExpansionEvents :many
SELECT replay_id, source_player_id, seconds_from_game_start
FROM replay_events
WHERE event_type = 'expansion'
  AND source_player_id IS NOT NULL
`

type ListExpansionEventsRow struct {
	ReplayID             int64
	SourcePlayerID       *int64
	SecondsFromGameStart int64
}

func (q *Queries) ListExpansionEvents(ctx context.Context) ([]ListExpansionEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListExpansionEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpansionEventsRow{}
	for rows.Next() {
		var i ListExpansionEventsRow
		if err := rows.Scan(&i.ReplayID, &i.SourcePlayerID, &i.SecondsFromGameStart); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListGasTimingRows = `-- name: ListGasTimingRows :many
SELECT c.player_id, c.seconds_from_game_start, COALESCE(c.unit_type, '') AS unit_type
FROM commands c
WHERE c.replay_id = ?
  AND c.action_type = 'Build'
  AND c.unit_type IN ('Assimilator', 'Extractor', 'Refinery')
ORDER BY c.player_id ASC, c.seconds_from_game_start ASC
`

type ListGasTimingRowsRow struct {
	PlayerID             int64
	SecondsFromGameStart int64
	UnitType             string
}

func (q *Queries) ListGasTimingRows(ctx context.Context, replayID int64) ([]ListGasTimingRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListGasTimingRows, replayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGasTimingRowsRow{}
	for rows.Next() {
		var i ListGasTimingRowsRow
		if err := rows.Scan(&i.PlayerID, &i.SecondsFromGameStart, &i.UnitType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListHotkeyGamesRateByPlayer = `-- name: ListHotkeyGamesRateByPlayer :many
WITH game_level AS (
  SELECT
    lower(trim(p.name)) AS player_key,
    CASE WHEN SUM(CASE WHEN c.action_type = 'Hotkey' AND c.hotkey_type IS NOT NULL THEN 1 ELSE 0 END) > 0 THEN 100.0 ELSE 0.0 END AS metric_value
  FROM players p
  LEFT JOIN commands_low_value c ON c.player_id = p.id
  WHERE p.is_observer = 0
    AND lower(trim(coalesce(p.type, ''))) = 'human'
  GROUP BY p.id
)
SELECT player_key, AVG(metric_value) AS metric_value
FROM game_level
GROUP BY player_key
`

type ListHotkeyGamesRateByPlayerRow struct {
	PlayerKey   string
	MetricValue *float64
}

func (q *Queries) ListHotkeyGamesRateByPlayer(ctx context.Context) ([]ListHotkeyGamesRateByPlayerRow, error) {
	rows, err := q.db.QueryContext(ctx, ListHotkeyGamesRateByPlayer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHotkeyGamesRateByPlayerRow{}
	for rows.Next() {
		var i ListHotkeyGamesRateByPlayerRow
		if err := rows.Scan(&i.PlayerKey, &i.MetricValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListPlayerChatRows = `-- name: ListPlayerChatRows :many
SELECT c.replay_id, COALESCE(c.chat_message, '') AS chat_message
FROM commands c
JOIN players p ON p.id = c.player_id
JOIN replays r ON r.id = c.replay_id
WHERE lower(trim(p.name)) = ?
  AND p.is_observer = 0
  AND c.action_type = 'Chat'
  AND c.chat_message IS NOT NULL
  AND trim(c.chat_message) <> ''
ORDER BY r.replay_date DESC, c.replay_id DESC, c.seconds_from_game_start DESC
`

type ListPlayerChatRowsRow struct {
	ReplayID    int64
	ChatMessage string
}

func (q *Queries) ListPlayerChatRows(ctx context.Context, name string) ([]ListPlayerChatRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListPlayerChatRows, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerChatRowsRow{}
	for rows.Next() {
		var i ListPlayerChatRowsRow
		if err := rows.Scan(&i.ReplayID, &i.ChatMessage); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListPlayersByReplayRows = `-- name: ListPlayersByReplayRows :many
SELECT replay_id, id AS player_id, name
FROM players
WHERE is_observer = 0
`

type ListPlayersByReplayRowsRow struct {
	ReplayID int64
	PlayerID int64
	Name     string
}

func (q *Queries) ListPlayersByReplayRows(ctx context.Context) ([]ListPlayersByReplayRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListPlayersByReplayRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayersByReplayRowsRow{}
	for rows.Next() {
		var i ListPlayersByReplayRowsRow
		if err := rows.Scan(&i.ReplayID, &i.PlayerID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListRaceOrderRows = `-- name: ListRaceOrderRows :many
SELECT p.id, p.race, c.action_type, c.tech_name, c.upgrade_name, c.seconds_from_game_start
FROM players p
JOIN commands c ON c.player_id = p.id
WHERE lower(trim(p.name)) = ?
  AND p.is_observer = 0
  AND (
    (c.action_type = 'Tech' AND c.tech_name IS NOT NULL AND c.tech_name <> '')
    OR
    (c.action_type = 'Upgrade' AND c.upgrade_name IS NOT NULL AND c.upgrade_name <> '')
  )
ORDER BY p.id ASC, c.seconds_from_game_start ASC
`

type ListRaceOrderRowsRow struct {
	ID                   int64
	Race                 string
	ActionType           string
	TechName             *string
	UpgradeName          *string
	SecondsFromGameStart int64
}

func (q *Queries) ListRaceOrderRows(ctx context.Context, name string) ([]ListRaceOrderRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListRaceOrderRows, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRaceOrderRowsRow{}
	for rows.Next() {
		var i ListRaceOrderRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Race,
			&i.ActionType,
			&i.TechName,
			&i.UpgradeName,
			&i.SecondsFromGameStart,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTechTimingRows = `-- name: ListTechTimingRows :many
SELECT c.player_id, c.seconds_from_game_start, COALESCE(c.tech_name, '') AS tech_name
FROM commands c
WHERE c.replay_id = ?
  AND c.action_type = 'Tech'
  AND c.tech_name IS NOT NULL
  AND c.tech_name <> ''
ORDER BY c.player_id ASC, c.seconds_from_game_start ASC
`

type ListTechTimingRowsRow struct {
	PlayerID             int64
	SecondsFromGameStart int64
	TechName             string
}

func (q *Queries) ListTechTimingRows(ctx context.Context, replayID int64) ([]ListTechTimingRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListTechTimingRows, replayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTechTimingRowsRow{}
	for rows.Next() {
		var i ListTechTimingRowsRow
		if err := rows.Scan(&i.PlayerID, &i.SecondsFromGameStart, &i.TechName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListUpgradeTimingRows = `-- name: ListUpgradeTimingRows :many
SELECT c.player_id, c.seconds_from_game_start, COALESCE(c.upgrade_name, '') AS upgrade_name
FROM commands c
WHERE c.replay_id = ?
  AND c.action_type = 'Upgrade'
  AND c.upgrade_name IS NOT NULL
  AND c.upgrade_name <> ''
ORDER BY c.player_id ASC, c.seconds_from_game_start ASC
`

type ListUpgradeTimingRowsRow struct {
	PlayerID             int64
	SecondsFromGameStart int64
	UpgradeName          string
}

func (q *Queries) ListUpgradeTimingRows(ctx context.Context, replayID int64) ([]ListUpgradeTimingRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListUpgradeTimingRows, replayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUpgradeTimingRowsRow{}
	for rows.Next() {
		var i ListUpgradeTimingRowsRow
		if err := rows.Scan(&i.PlayerID, &i.SecondsFromGameStart, &i.UpgradeName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
