// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package sqlcgen

import (
	"context"
)

const CountReplays = `-- name: CountReplays :one
SELECT COUNT(*) AS total_replays
FROM replays
`

func (q *Queries) CountReplays(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountReplays)
	var total_replays int64
	err := row.Scan(&total_replays)
	return total_replays, err
}

const GetIngestInputDir = `-- name: GetIngestInputDir :one
SELECT ingest_input_dir
FROM settings
WHERE config_key = ?
`

func (q *Queries) GetIngestInputDir(ctx context.Context, configKey string) (string, error) {
	row := q.db.QueryRowContext(ctx, GetIngestInputDir, configKey)
	var ingest_input_dir string
	err := row.Scan(&ingest_input_dir)
	return ingest_input_dir, err
}

const GetReplayFilePathByID = `-- name: GetReplayFilePathByID :one
SELECT file_path
FROM replays
WHERE id = ?
`

func (q *Queries) GetReplayFilePathByID(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, GetReplayFilePathByID, id)
	var file_path string
	err := row.Scan(&file_path)
	return file_path, err
}

const ListTopPlayerColorRows = `-- name: ListTopPlayerColorRows :many
SELECT lower(trim(name)) AS player_key, COUNT(*) AS games
FROM players
WHERE is_observer = 0
GROUP BY lower(trim(name))
ORDER BY games DESC, player_key ASC
LIMIT 15
`

type ListTopPlayerColorRowsRow struct {
	PlayerKey string
	Games     int64
}

func (q *Queries) ListTopPlayerColorRows(ctx context.Context) ([]ListTopPlayerColorRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListTopPlayerColorRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopPlayerColorRowsRow{}
	for rows.Next() {
		var i ListTopPlayerColorRowsRow
		if err := rows.Scan(&i.PlayerKey, &i.Games); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SetIngestInputDir = `-- name: SetIngestInputDir :exec
UPDATE settings
SET ingest_input_dir = ?, updated_at = CURRENT_TIMESTAMP
WHERE config_key = ?
`

type SetIngestInputDirParams struct {
	IngestInputDir string
	ConfigKey      string
}

func (q *Queries) SetIngestInputDir(ctx context.Context, arg SetIngestInputDirParams) error {
	_, err := q.db.ExecContext(ctx, SetIngestInputDir, arg.IngestInputDir, arg.ConfigKey)
	return err
}
