// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: unit_cadence_static.sql

package sqlcgen

import (
	"context"
)

const ListFirstUnitCommandRows = `-- name: ListFirstUnitCommandRows :many
SELECT c.player_id, c.seconds_from_game_start, c.action_type, c.unit_type, c.unit_types
FROM commands c
WHERE c.replay_id = ?
  AND c.action_type IN ('Build', 'Train', 'Unit Morph')
ORDER BY c.player_id ASC, c.seconds_from_game_start ASC, c.id ASC
`

type ListFirstUnitCommandRowsRow struct {
	PlayerID             int64
	SecondsFromGameStart int64
	ActionType           string
	UnitType             *string
	UnitTypes            *string
}

func (q *Queries) ListFirstUnitCommandRows(ctx context.Context, replayID int64) ([]ListFirstUnitCommandRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListFirstUnitCommandRows, replayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFirstUnitCommandRowsRow{}
	for rows.Next() {
		var i ListFirstUnitCommandRowsRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.SecondsFromGameStart,
			&i.ActionType,
			&i.UnitType,
			&i.UnitTypes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListUnitSliceCommandRows = `-- name: ListUnitSliceCommandRows :many
SELECT c.player_id, c.seconds_from_game_start, c.unit_type
FROM commands c
WHERE c.replay_id = ?
  AND c.action_type IN ('Train', 'Unit Morph', 'Building Morph', 'Build')
  AND c.unit_type IS NOT NULL
  AND c.unit_type <> ''
ORDER BY c.seconds_from_game_start ASC, c.player_id ASC
`

type ListUnitSliceCommandRowsRow struct {
	PlayerID             int64
	SecondsFromGameStart int64
	UnitType             *string
}

func (q *Queries) ListUnitSliceCommandRows(ctx context.Context, replayID int64) ([]ListUnitSliceCommandRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListUnitSliceCommandRows, replayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnitSliceCommandRowsRow{}
	for rows.Next() {
		var i ListUnitSliceCommandRowsRow
		if err := rows.Scan(&i.PlayerID, &i.SecondsFromGameStart, &i.UnitType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
