// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: viewport.sql

package sqlcgen

import (
	"context"
)

const ListViewportAggregateRows = `-- name: ListViewportAggregateRows :many
SELECT
  lower(trim(p.name)) AS player_key,
  CAST(MIN(p.name) AS TEXT) AS player_name,
  COALESCE(dp.value_string, '') AS raw_value
FROM detected_patterns_replay_player dp
JOIN players p
  ON p.id = dp.player_id
WHERE dp.pattern_name = ?
  AND p.is_observer = 0
  AND lower(trim(coalesce(p.type, ''))) = 'human'
  AND dp.value_string IS NOT NULL
  AND trim(dp.value_string) <> ''
GROUP BY player_key, dp.replay_id, dp.player_id, dp.value_string
ORDER BY player_key ASC, player_name ASC
`

type ListViewportAggregateRowsRow struct {
	PlayerKey  string
	PlayerName string
	RawValue   string
}

func (q *Queries) ListViewportAggregateRows(ctx context.Context, patternName string) ([]ListViewportAggregateRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListViewportAggregateRows, patternName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListViewportAggregateRowsRow{}
	for rows.Next() {
		var i ListViewportAggregateRowsRow
		if err := rows.Scan(&i.PlayerKey, &i.PlayerName, &i.RawValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListViewportGameRows = `-- name: ListViewportGameRows :many
SELECT player_id, COALESCE(value_string, '') AS raw_value
FROM detected_patterns_replay_player
WHERE replay_id = ?
  AND pattern_name = ?
  AND value_string IS NOT NULL
  AND trim(value_string) <> ''
`

type ListViewportGameRowsParams struct {
	ReplayID    int64
	PatternName string
}

type ListViewportGameRowsRow struct {
	PlayerID int64
	RawValue string
}

func (q *Queries) ListViewportGameRows(ctx context.Context, arg ListViewportGameRowsParams) ([]ListViewportGameRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListViewportGameRows, arg.ReplayID, arg.PatternName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListViewportGameRowsRow{}
	for rows.Next() {
		var i ListViewportGameRowsRow
		if err := rows.Scan(&i.PlayerID, &i.RawValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
