// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflow_static.sql

package sqlcgen

import (
	"context"
)

const CountWorkflowDurationBuckets = `-- name: CountWorkflowDurationBuckets :one
SELECT
  CAST(COALESCE(SUM(CASE WHEN duration_seconds < 600 THEN 1 ELSE 0 END), 0) AS INTEGER) AS under_10m,
  CAST(COALESCE(SUM(CASE WHEN duration_seconds >= 600 AND duration_seconds < 1200 THEN 1 ELSE 0 END), 0) AS INTEGER) AS m10_20,
  CAST(COALESCE(SUM(CASE WHEN duration_seconds >= 1200 AND duration_seconds < 1800 THEN 1 ELSE 0 END), 0) AS INTEGER) AS m20_30,
  CAST(COALESCE(SUM(CASE WHEN duration_seconds >= 1800 AND duration_seconds < 2700 THEN 1 ELSE 0 END), 0) AS INTEGER) AS m30_45,
  CAST(COALESCE(SUM(CASE WHEN duration_seconds >= 2700 THEN 1 ELSE 0 END), 0) AS INTEGER) AS m45_plus
FROM replays
`

type CountWorkflowDurationBucketsRow struct {
	Under10m int64
	M1020    int64
	M2030    int64
	M3045    int64
	M45Plus  int64
}

func (q *Queries) CountWorkflowDurationBuckets(ctx context.Context) (CountWorkflowDurationBucketsRow, error) {
	row := q.db.QueryRowContext(ctx, CountWorkflowDurationBuckets)
	var i CountWorkflowDurationBucketsRow
	err := row.Scan(
		&i.Under10m,
		&i.M1020,
		&i.M2030,
		&i.M3045,
		&i.M45Plus,
	)
	return i, err
}

const ListWorkflowFilterMaps = `-- name: ListWorkflowFilterMaps :many
SELECT CAST(MIN(map_name) AS TEXT) AS map_name, COUNT(*) AS games
FROM replays
GROUP BY lower(trim(map_name))
ORDER BY games DESC, map_name ASC
LIMIT 15
`

type ListWorkflowFilterMapsRow struct {
	MapName string
	Games   int64
}

func (q *Queries) ListWorkflowFilterMaps(ctx context.Context) ([]ListWorkflowFilterMapsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListWorkflowFilterMaps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkflowFilterMapsRow{}
	for rows.Next() {
		var i ListWorkflowFilterMapsRow
		if err := rows.Scan(&i.MapName, &i.Games); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListWorkflowFilterPlayers = `-- name: ListWorkflowFilterPlayers :many
SELECT lower(trim(name)) AS player_key, CAST(MIN(name) AS TEXT) AS player_name, COUNT(*) AS games
FROM players
WHERE is_observer = 0
GROUP BY lower(trim(name))
HAVING COUNT(*) >= 5
ORDER BY games DESC, player_name ASC
LIMIT 200
`

type ListWorkflowFilterPlayersRow struct {
	PlayerKey  string
	PlayerName string
	Games      int64
}

func (q *Queries) ListWorkflowFilterPlayers(ctx context.Context) ([]ListWorkflowFilterPlayersRow, error) {
	rows, err := q.db.QueryContext(ctx, ListWorkflowFilterPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkflowFilterPlayersRow{}
	for rows.Next() {
		var i ListWorkflowFilterPlayersRow
		if err := rows.Scan(&i.PlayerKey, &i.PlayerName, &i.Games); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
